import{days,genres}from'./domain/game.js';import{artists,artwork}from'./data/artists.js';
import{connect,ensureSession,saveSession,listDrafts,listTeams,listActivityCodes,releaseTeam,setSubmissionStatus,watchSession,transition,reopenDay,backend,activityId,status as storeStatus}from'./services/store.js';
import{syncedArtwork,releaseInfo as syncedReleaseInfo}from'./data/covers.generated.js';
import{localArtwork}from'./data/covers.local.js';
import{recomputeSubmission}from'./domain/submissions.js';
import{politicaDe,POLITICAS}from'./domain/equipos.js';
import{normalizarCodigo,conflictoDeCodigo,ordenarPartidas,elegirPartida}from'./domain/partidas.js';
import{openTeacherGate}from'./services/admin-gate.js';
const $=s=>document.querySelector(s);const rememberedCode=localStorage.getItem('musicfest:admin:last-code')||'DEMO';
const teacher=await openTeacherGate();
await connect({code:rememberedCode,role:'admin',ownerUid:teacher?.uid});
// Toda sesión que entra al panel —la inicial y las que llegan por snapshot o
// por otra pestaña— pasa por aquí. Antes esto se hacía sólo al arrancar y una
// actualización remota podía dejar el panel con `customArtists` indefinido.
function normalizeSession(s){
s.events=s.events||[];s.days=s.days||days.map(d=>structuredClone(d));s.customArtists=s.customArtists||[];s.artistOverrides=s.artistOverrides||{};s.deletedArtistIds=s.deletedArtistIds||[];s.activeArtistIds=s.activeArtistIds||artists.map(a=>a.id);
// En Firebase el catálogo ya vive en Firestore: volver a mezclar las semillas
// resucitaría carátulas que el docente eliminó a propósito.
s.artwork=backend==='firebase'?(s.artwork||{}):{...syncedArtwork,...artwork,...(s.artwork||{})};
// Si la carátula ya está en el repositorio, esa copia es la definitiva: se
// sirve desde el mismo origen y no depende de que un CDN ajeno siga en pie.
s.artwork={...s.artwork,...localArtwork};
s.releaseInfo=backend==='firebase'?(s.releaseInfo||{}):{...syncedReleaseInfo,...(s.releaseInfo||{})};
s.catalogLocked=s.catalogLocked||false;return s}
let session=normalizeSession(ensureSession(rememberedCode)),editorDayIndex=0,deliveryFilter='all',catalogQuery='',coverFilter='all',editingArtistId=null;
localStorage.setItem('musicfest:admin:last-code',session.code);
// En modo demo, dejar la sesión completa en localStorage desde el arranque para
// que la vista estudiante y las otras pestañas lean siempre la misma forma.
if(backend!=='firebase')saveSession(session);
const allArtists=()=>[...artists,...session.customArtists].filter((a,i,list)=>!session.deletedArtistIds.includes(a.id)&&list.findIndex(x=>x.id===a.id)===i).map(a=>({...a,...(session.artistOverrides[a.id]||{})}));const activeArtists=()=>allArtists().filter(a=>session.activeArtistIds.includes(a.id));const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const activeDays=()=>session.days;
function exportActivity(){const payload={format:'musicfest-activity',version:1,exportedAt:new Date().toISOString(),session:{...session,events:session.events||[]},catalog:{baseArtistIds:artists.map(a=>a.id),customArtists:session.customArtists,artistOverrides:session.artistOverrides,deletedArtistIds:session.deletedArtistIds,activeArtistIds:session.activeArtistIds,artwork:session.artwork,releaseInfo:session.releaseInfo}};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`musicfest-${session.code.toLowerCase()}-${new Date().toISOString().slice(0,10)}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);log('export','Configuración exportada a un archivo JSON.');persist()}
const exportButton=document.createElement('button');exportButton.id='exportActivity';exportButton.type='button';exportButton.textContent='Exportar configuración';$('#saveIdentity').insertAdjacentElement('afterend',exportButton);exportButton.onclick=exportActivity;
const formDraftKey=()=>`musicfest:admin-form:${session.code}`;const formFields=['activityName','activityCode','rArtists','rBudget','rDuration','rChilean','rGenres','rPop','rRock','rRap','rTrap','newName','newCountry','newCost','newPopularity','newDuration','newCover'];function saveFormDraft(){const draft=Object.fromEntries(formFields.map(id=>[id,$(`#${id}`)?.value??'']));draft.editorDayIndex=editorDayIndex;localStorage.setItem(formDraftKey(),JSON.stringify(draft));$('#coverStatus')?.setAttribute('data-draft','Cambios de formulario guardados localmente')}function restoreFormDraft(){const draft=JSON.parse(localStorage.getItem(formDraftKey())||'null');if(!draft)return;formFields.forEach(id=>{const field=$(`#${id}`);if(field&&draft[id]!==undefined)field.value=draft[id]});if(Number.isInteger(draft.editorDayIndex)){editorDayIndex=draft.editorDayIndex;renderRuleEditor()}if(draft.newCover)updateCoverPreview(draft.newCover)}function clearFormDraft(){localStorage.removeItem(formDraftKey())}
const selectedCoverPreview=document.createElement('div');selectedCoverPreview.id='selectedCoverPreview';selectedCoverPreview.className='selected-cover-preview empty';$('#newCover').closest('label').insertAdjacentElement('beforebegin',selectedCoverPreview);function updateCoverPreview(url,info={}){const clean=String(url||'').trim();selectedCoverPreview.classList.toggle('empty',!clean);selectedCoverPreview.innerHTML=clean?`<div><img src="${esc(clean)}" alt="Vista previa de la carátula"><span>VISTA PREVIA</span></div><p><small>CARÁTULA SELECCIONADA</small><b>${esc(info.album||'Imagen cargada manualmente')}</b><em>${esc(info.year||'Revisa el encuadre antes de guardar')}</em></p>`:'<p><small>VISTA PREVIA</small><b>Selecciona o pega una carátula</b><em>Aparecerá aquí en formato cuadrado.</em></p>';const img=selectedCoverPreview.querySelector('img');if(img)img.onerror=()=>{selectedCoverPreview.classList.add('load-error');selectedCoverPreview.querySelector('p em').textContent='No fue posible cargar esta URL.'}}
function log(type,text){session.events.unshift({type,text,at:new Date().toISOString()});session.events=session.events.slice(0,20)}
function persist(){saveSession(session);render();renderCatalog()}
function render(){const gameDays=activeDays(),day=gameDays[session.activeDayIndex];$('#adminState').textContent=session.state==='lobby'?'Lobby':session.state==='active'?'En curso':session.state==='paused'?'Pausada':'Cerrada';$('#adminDay').textContent=session.mode==='simultaneous'?'Festival completo':day.name;$('#ruleDay').textContent=day.name;$('#modeLabel').textContent=session.mode==='sequential'?'Modo secuencial · un día a la vez':'Modo simultáneo · tres días a la vez';$('#roundProgress').innerHTML=gameDays.map((d,i)=>`<span class="${i===session.activeDayIndex?'active':''}">${i+1} · ${d.name}</span>`).join(' ');$('#ruleSummary').innerHTML=[['Artistas',day.artistCount],['Presupuesto',day.budget],['Duración',`${day.duration} h`],['Chilenos',`${day.minChilean}+`],['Géneros',day.minGenres]].map(x=>`<div class="rule-item"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');document.querySelectorAll('.mode-select button').forEach(b=>b.classList.toggle('active',b.dataset.mode===session.mode));$('#eventLog').innerHTML=(session.events.length?session.events:[{text:'Partida demo creada.',at:new Date().toISOString()}]).map(e=>`<li><b>${new Date(e.at).toLocaleTimeString('es-CL',{hour:'2-digit',minute:'2-digit'})}</b> · ${e.text}</li>`).join('');$('#back').disabled=session.mode==='simultaneous'||session.activeDayIndex===0;$('#advance').disabled=session.mode==='simultaneous'||session.activeDayIndex===2;$('#activityName').value=session.name||'';$('#activityCode').value=session.code||'';renderRuleEditor();renderDeliveries();renderTeams()}
function renderRuleEditor(){const gameDays=activeDays(),d=gameDays[editorDayIndex];$('#editorDay').textContent=d.name;$('#ruleTabs').innerHTML=gameDays.map((x,i)=>`<button data-rule-day="${i}" class="${i===editorDayIndex?'active':''}">${x.name}</button>`).join('');$('#rArtists').value=d.artistCount;$('#rBudget').value=d.budget;$('#rDuration').value=d.duration;$('#rChilean').value=d.minChilean;$('#rGenres').value=d.minGenres;$('#rPop').value=d.genreMinimums?.Pop||0;$('#rRock').value=d.genreMinimums?.Rock||0;$('#rRap').value=d.genreMinimums?.Rap||0;$('#rTrap').value=d.genreMinimums?.['Trap Latino']||0}
function renderCatalog(){const active=activeArtists(),counts=Object.fromEntries(genres.map(g=>[g,active.filter(a=>a.genre===g).length])),covered=active.filter(a=>session.artwork[a.id]).length,enRepo=active.filter(a=>localArtwork[a.id]).length,porBajar=active.filter(a=>session.artwork[a.id]&&!localArtwork[a.id]).length,pending=active.filter(a=>session.releaseInfo[a.id]?.review==='pending').length;$('#genreSummary').innerHTML=`<span><b>${active.length}</b><small>ACTIVOS</small></span>${genres.map(g=>`<span><b>${counts[g]}</b><small>${g.toUpperCase()}</small></span>`).join('')}<span><b>${enRepo}</b><small>EN EL REPO</small></span><span><b>${porBajar}</b><small>POR BAJAR</small></span><span><b>${pending}</b><small>POR REVISAR</small></span><button id="toggleCatalogLock" class="catalog-lock ${session.catalogLocked?'locked':''}">${session.catalogLocked?'POOL CERRADO · REABRIR':'CERRAR POOL'}</button>`;const visible=allArtists().filter(a=>a.name.toLowerCase().includes(catalogQuery));$('#catalogList').innerHTML=visible.map(a=>{const on=session.activeArtistIds.includes(a.id),cover=session.artwork[a.id],review=session.releaseInfo[a.id]?.review,coverLabel=!cover?'SIN COVER':review==='approved'?'COVER APROBADO':'REVISAR COVER',disabled=session.catalogLocked?'disabled':'';return`<div class="catalog-row ${on?'active':''}"><button class="catalog-main" data-pool="${a.id}" aria-pressed="${on}" ${disabled}><span class="catalog-thumb">${cover?`<img src="${esc(cover)}" alt="">`:esc(a.name.split(/\s+/).map(x=>x[0]).join('').slice(0,2))}</span><span><b>${esc(a.name)}</b><small>${a.genre} · ${a.country} · $${a.cost} · ★${a.popularity} · ${a.duration}h</small><em class="cover-review ${review||'missing'}">${coverLabel}</em></span><i>${on?'EN JUEGO':'FUERA'}</i></button><span class="catalog-actions"><button data-edit="${a.id}" aria-label="Editar ${esc(a.name)}" ${disabled}>EDITAR</button><button data-delete="${a.id}" aria-label="Eliminar ${esc(a.name)}" ${disabled}>×</button></span></div>`}).join('');$('#selectAllArtists').disabled=session.catalogLocked;$('#clearArtists').disabled=session.catalogLocked;$('#addArtist').disabled=session.catalogLocked}
function loadArtistEditor(id){const a=allArtists().find(x=>x.id===id);if(!a)return;editingArtistId=id;$('#newName').value=a.name;$('#newGenre').value=a.genre;$('#newCountry').value=a.country;$('#newCost').value=a.cost;$('#newPopularity').value=a.popularity;$('#newDuration').value=a.duration;$('#newCover').value=session.artwork[id]||'';updateCoverPreview(session.artwork[id],session.releaseInfo[id]);$('.artist-creator h3').textContent=`Editar · ${a.name}`;$('#addArtist').textContent='Guardar cambios';$('#coverStatus').textContent=localArtwork[id]?`Esta carátula vive en el repositorio y pisa lo que elijas aquí: guardar no la cambia. Para reemplazarla: npm run covers:download -- --only ${id} --url DIRECCION_DE_LA_IMAGEN`:'Puedes modificar los datos o buscar otra carátula.';$('.artist-creator').scrollIntoView({behavior:'smooth',block:'start'})}
function resetArtistEditor(message='Artista agregado y activado para esta actividad.'){editingArtistId=null;['#newName','#newCountry','#newCost','#newPopularity','#newDuration','#newCover'].forEach(s=>$(s).value='');$('#coverResults').innerHTML='';updateCoverPreview('');clearFormDraft();$('.artist-creator h3').textContent='Agregar al cartel';$('#addArtist').textContent='Agregar artista al juego';$('#coverStatus').textContent=message}
function slugify(value){return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')}
async function findCovers(){const name=$('#newName').value.trim();if(!name){$('#coverStatus').textContent='Escribe primero el nombre del artista.';return}$('#coverStatus').textContent='Buscando álbumes…';$('#coverResults').innerHTML='';try{const url=`https://itunes.apple.com/search?term=${encodeURIComponent(name)}&entity=album&attribute=artistTerm&country=cl&limit=50`;const response=await fetch(url);if(!response.ok)throw new Error();const data=await response.json(),needle=name.toLowerCase(),matches=data.results.filter(x=>x.artworkUrl100&&(x.trackCount||0)>=4&&String(x.artistName||'').toLowerCase().includes(needle)).sort((a,b)=>new Date(b.releaseDate)-new Date(a.releaseDate)).slice(0,6);$('#coverStatus').textContent=matches.length?'Selecciona la carátula correcta. Se muestran primero los álbumes y EP más recientes.':'No encontramos álbumes; puedes pegar una URL manualmente.';$('#coverResults').innerHTML=matches.map(x=>{const image=x.artworkUrl100.replace('100x100bb','600x600bb');return`<button data-cover="${esc(image)}" title="${esc(x.collectionName)}"><img src="${esc(image)}" alt=""><span>${esc(x.collectionName)}<small>${String(x.releaseDate||'').slice(0,4)}</small></span></button>`}).join('')}catch{$('#coverStatus').textContent='No fue posible consultar el catálogo. Puedes pegar una URL manualmente.'}}
// Equipos conectados. Existe por una razón concreta: dos grupos que eligen el
// mismo nombre caen en el mismo documento y comparten borrador, y hasta ahora
// eso era invisible desde el panel. Los correos declarados al entrar son lo que
// permite distinguirlos, y "Liberar" devuelve el nombre sin tocar el trabajo.
function renderTeams(){const casilla=$('#uniqueNames');if(casilla)casilla.checked=politicaDe(session)===POLITICAS.UNICA;
const lista=$('#teamList');if(!lista)return;
const equipos=[...(listTeams(session.code)||[])].sort((a,b)=>String(a.name||a.id||'').localeCompare(String(b.name||b.id||''),'es'));
if(!equipos.length){lista.innerHTML='<div class="empty-teams">Todavía no ha entrado ningún equipo a esta partida.</div>';return}
lista.innerHTML=equipos.map(team=>{
// En modo demo los equipos se deducen de los borradores y no hay membresía:
// `memberUids` ausente no es lo mismo que un equipo sin nadie dentro.
const miembros=Array.isArray(team.memberUids)?team.memberUids:null,libre=miembros!==null&&miembros.length===0,correos=team.memberEmails||[];
const rotulo=miembros===null?'EQUIPO LOCAL':libre?'LIBRE · SIN NADIE DENTRO':`${miembros.length} DISPOSITIVO${miembros.length===1?'':'S'}`;
const cuerpo=correos.length?`<ul class="team-emails">${correos.map(c=>`<li>${esc(c)}</li>`).join('')}</ul>`:'<ul class="team-emails is-empty"><li>Sin correos declarados</li></ul>';
return `<article class="team-card${libre?' is-free':''}"><h3>${esc(team.name||team.id)}</h3><small>${rotulo}</small>${cuerpo}<button data-release="${esc(team.id)}"${libre||miembros===null?' disabled':''}>Liberar nombre</button></article>`}).join('')}
function renderDeliveries(){const records=[];for(const draft of listDrafts(session.code)){for(const [dayId,sub] of Object.entries(draft.submissions||{})){if(sub.revision!==session.revision&&sub.validationStatus!=='returned')continue;records.push({team:draft.team,dayId,...sub})}}const filtered=records.filter(r=>deliveryFilter==='all'||r.validationStatus===deliveryFilter);$('#deliveryList').innerHTML=filtered.length?filtered.sort((a,b)=>new Date(b.submittedAt)-new Date(a.submittedAt)).map(deliveryCard).join(''):'<div class="empty-deliveries"><b>Aún no hay entregas en esta vista.</b><span>Las entregas aparecerán aquí cuando los equipos envíen sus lineups.</span></div>'}
// El panel docente NO confía en los totales enviados por el estudiante: los
// recalcula desde `selections` con el pool y las reglas vigentes. Si difieren,
// la tarjeta lo advierte y la validación queda bloqueada hasta revisarlo.
function deliveryCard(r){const pool=allArtists(),check=recomputeSubmission({...r,reportedTotals:r.totals},{days:activeDays(),artists:pool}),t=check.totals,byId=new Map(pool.map(a=>[a.id,a])),selected=r.selections.map(id=>byId.get(id)).filter(Boolean),rule=check.day||{},genreText=genres.map(g=>`${g}: ${t.genres[g]||0}`).join(' · '),status=r.validationStatus||'pending',label=status==='validated'?'VALIDADO':status==='returned'?'DEVUELTO':'PENDIENTE',verdict=check.valid?'CUMPLE TODAS LAS RESTRICCIONES':'NO CUMPLE',failed=check.checks.filter(c=>!c[1]).map(c=>`${c[0]} ${c[2]}`).join(' · ');
return`<article class="delivery-card ${status} ${check.valid?'rule-ok':'rule-fail'}"><header><div><small>${esc(r.dayName||'').toUpperCase()} · REV. ${r.revision}</small><h3>${esc(r.team)}</h3></div><b>${label}</b></header>
<div class="delivery-metrics"><span><b>${t.count}/${rule.artistCount??'–'}</b><small>ARTISTAS</small></span><span><b>$${t.cost}/$${rule.budget??'–'}</b><small>COSTO / PRESUP.</small></span><span><b>${t.duration}/${rule.duration??'–'}h</b><small>DURACIÓN</small></span><span><b>${t.chilean}/${rule.minChilean??'–'}</b><small>CHILENOS / MÍN.</small></span><span><b>${t.score}</b><small>POPULARIDAD</small></span></div>
<div class="delivery-detail"><p><b>ARTISTAS SELECCIONADOS</b>${selected.map(a=>esc(a.name)).join(' · ')||'—'}</p><p><b>ARTISTAS POR GÉNERO</b>${genreText}</p><p class="delivery-verdict ${check.valid?'ok':'fail'}"><b>RECÁLCULO DEL SERVIDOR</b>${verdict}${failed?` · ${esc(failed)}`:''}</p>${check.tampered?`<p class="delivery-alert"><b>REVISAR</b>${check.deltas.map(esc).join(' · ')}</p>`:''}</div>
<footer><time>${new Date(r.submittedAt).toLocaleString('es-CL')}</time><div><button data-return="${encodeURIComponent(r.team)}|${r.dayId}">Devolver</button><button data-validate="${encodeURIComponent(r.team)}|${r.dayId}" ${check.valid?'':'disabled title="El recálculo no cumple las restricciones"'}>Validar entrega</button></div></footer></article>`}
// Avance, retroceso, pausa, cierre y reapertura son operaciones autoritativas:
// se resuelven en una transacción sobre el documento de actividad para que dos
// pestañas docentes abiertas no puedan dejar la sesión en estados distintos.
async function control(kind,options){const buttons=[...document.querySelectorAll('.control-buttons button')];buttons.forEach(b=>b.disabled=true);
try{await(kind==='reopen'?reopenDay(session.code,options.dayIndex):transition(session.code,kind,options));
session=ensureSession(session.code);render();renderCatalog()}
catch(error){alert(error.message||'No fue posible completar la operación.')}
finally{buttons.forEach(b=>b.disabled=false);render()}}
$('#start').onclick=()=>control('start');$('#pause').onclick=()=>control('pause');$('#advance').onclick=()=>control('advance');$('#back').onclick=()=>control('back');$('#close').onclick=()=>control('close');
document.querySelectorAll('.mode-select button').forEach(b=>b.onclick=()=>{session.mode=b.dataset.mode;session.activeDayIndex=0;log('mode',`Modalidad cambiada a ${b.dataset.mode}.`);persist()});
$('#saveIdentity').onclick=()=>{const previous=session.code,destino=normalizarCodigo($('#activityCode').value)||'DEMO',choque=conflictoDeCodigo({codigo:destino,mapa:mapaDeCodigos,activityIdActual:activityId()});$('#activityMsg').textContent='';if(choque){$('#activityMsg').textContent=choque;$('#activityCode').value=previous;return}session.name=$('#activityName').value.trim()||'MusicFest';session.code=destino;localStorage.setItem('musicfest:admin:last-code',session.code);log('identity',`Identidad actualizada${previous!==session.code?` · nuevo código ${session.code}`:''}.`);persist()};
$('#ruleTabs').onclick=e=>{if(e.target.dataset.ruleDay===undefined)return;editorDayIndex=Number(e.target.dataset.ruleDay);renderRuleEditor()};$('#saveRules').onclick=()=>{const d=activeDays()[editorDayIndex];Object.assign(d,{artistCount:Number($('#rArtists').value),budget:Number($('#rBudget').value),duration:Number($('#rDuration').value),minChilean:Number($('#rChilean').value),minGenres:Number($('#rGenres').value),genreMinimums:{Pop:Number($('#rPop').value),Rock:Number($('#rRock').value),Rap:Number($('#rRap').value),'Trap Latino':Number($('#rTrap').value)}});log('rules',`Reglas de ${d.name} actualizadas.`);persist()};
$('#reopen').onclick=()=>{$('#reopenDayName').textContent=activeDays()[session.activeDayIndex].name;$('#reopenDialog').showModal()};$('#cancelReopen').onclick=()=>$('#reopenDialog').close();$('#confirmReopen').onclick=async()=>{$('#reopenDialog').close();await control('reopen',{dayIndex:session.activeDayIndex})};
$('#catalogSearch').oninput=e=>{catalogQuery=e.target.value.trim().toLowerCase();renderCatalog()};$('#catalogList').onclick=e=>{const edit=e.target.closest('[data-edit]'),remove=e.target.closest('[data-delete]'),toggle=e.target.closest('[data-pool]');if(edit){loadArtistEditor(edit.dataset.edit);return}if(remove){const id=remove.dataset.delete,a=allArtists().find(x=>x.id===id);if(!a||!confirm(`¿Eliminar a ${a.name} del catálogo? Esta acción lo retirará también del pool de la actividad.`))return;session.deletedArtistIds.push(id);session.activeArtistIds=session.activeArtistIds.filter(x=>x!==id);delete session.artistOverrides[id];delete session.artwork[id];if(editingArtistId===id)resetArtistEditor('El artista fue eliminado del catálogo.');log('catalog',`${a.name} eliminado del catálogo.`);persist();return}if(!toggle)return;const id=toggle.dataset.pool,index=session.activeArtistIds.indexOf(id);if(index>=0)session.activeArtistIds.splice(index,1);else session.activeArtistIds.push(id);log('catalog',`${allArtists().find(a=>a.id===id)?.name} ${index>=0?'retirado del':'incorporado al'} pool.`);persist()};$('#selectAllArtists').onclick=()=>{session.activeArtistIds=allArtists().map(a=>a.id);persist()};$('#clearArtists').onclick=()=>{session.activeArtistIds=[];persist()};$('#findCovers').onclick=findCovers;$('#coverResults').onclick=e=>{const button=e.target.closest('[data-cover]');if(!button)return;$('#newCover').value=button.dataset.cover;document.querySelectorAll('[data-cover]').forEach(x=>x.classList.toggle('selected',x===button))};$('#addArtist').onclick=()=>{const name=$('#newName').value.trim(),genre=$('#newGenre').value,country=$('#newCountry').value.trim().toUpperCase(),cost=Number($('#newCost').value),popularity=Number($('#newPopularity').value),duration=Number($('#newDuration').value),cover=$('#newCover').value.trim();if(!name||!country||cost<0||popularity<1||popularity>5||duration<=0){$('#coverStatus').textContent='Completa todas las características con valores válidos.';return}if(editingArtistId){session.artistOverrides[editingArtistId]={name,genre,country,cost,popularity,duration};if(cover)session.artwork[editingArtistId]=cover;else delete session.artwork[editingArtistId];log('catalog',`${name} actualizado en el catálogo.`);resetArtistEditor('Cambios guardados correctamente.');persist();return}let id=slugify(name),suffix=2;while(allArtists().some(a=>a.id===id))id=`${slugify(name)}-${suffix++}`;session.customArtists.push({id,name,genre,country,cost,popularity,duration});session.activeArtistIds.push(id);if(cover)session.artwork[id]=cover;log('catalog',`${name} agregado al pool de artistas.`);resetArtistEditor();persist()};
$('#coverResults').addEventListener('click',e=>{const button=e.target.closest('[data-cover]');if(!button)return;updateCoverPreview(button.dataset.cover,{album:button.title,year:button.querySelector('small')?.textContent})});$('#newCover').addEventListener('input',e=>updateCoverPreview(e.target.value));
$('#genreSummary').onclick=e=>{if(e.target.id!=='toggleCatalogLock')return;session.catalogLocked=!session.catalogLocked;log('catalog',session.catalogLocked?`Pool cerrado con ${activeArtists().length} artistas.`:'Pool reabierto para edición.');persist()};
// Al guardar, la carátula elegida queda aprobada. La imagen sigue viviendo en
// el CDN de Apple Music hasta que `npm run covers:download` la baje al
// repositorio; desde ese momento se sirve desde GitHub Pages, mismo origen y
// sin depender de terceros. Ver docs/CARATULAS.md.
function promoteCover(artistId){const url=session.artwork[artistId];if(!url)return;
session.releaseInfo[artistId]={...(session.releaseInfo[artistId]||{}),review:'approved'};persist();
$('#coverStatus').textContent=/^https?:/.test(url)
?`Carátula aprobada. Bájala al repositorio con: npm run covers:download -- --code ${session.code} --only ${artistId}`
:'Carátula aprobada y servida desde el repositorio.'}
const saveArtistAction=$('#addArtist').onclick;$('#addArtist').onclick=()=>{const editedId=editingArtistId,before=new Set(session.customArtists.map(a=>a.id));saveArtistAction();
const targetId=editedId||session.customArtists.map(a=>a.id).find(id=>!before.has(id));if(targetId&&session.artwork[targetId])promoteCover(targetId)};
const baseCatalogRenderer=renderCatalog;renderCatalog=()=>{baseCatalogRenderer();const catalogue=allArtists(),totals={all:catalogue.length,pending:catalogue.filter(a=>session.artwork[a.id]&&session.releaseInfo[a.id]?.review!=='approved').length,missing:catalogue.filter(a=>!session.artwork[a.id]).length,approved:catalogue.filter(a=>session.artwork[a.id]&&session.releaseInfo[a.id]?.review==='approved').length,porbajar:catalogue.filter(a=>session.artwork[a.id]&&!localArtwork[a.id]).length};let filters=$('.catalog-cover-filters');if(!filters){filters=document.createElement('div');filters.className='catalog-cover-filters';$('#catalogSearch').insertAdjacentElement('afterend',filters)}filters.innerHTML=[['all','Todos'],['pending','Por confirmar'],['approved','Cover OK'],['porbajar','Por bajar'],['missing','Sin cover']].map(([key,label])=>`<button data-cover-filter="${key}" class="${coverFilter===key?'active':''}">${label}<b>${totals[key]}</b></button>`).join('');document.querySelectorAll('#catalogList .catalog-row').forEach(row=>{const id=row.querySelector('[data-pool]').dataset.pool,hasCover=Boolean(session.artwork[id]),approved=session.releaseInfo[id]?.review==='approved',porBajar=hasCover&&!localArtwork[id],show=coverFilter==='all'||coverFilter==='pending'&&hasCover&&!approved||coverFilter==='missing'&&!hasCover||coverFilter==='approved'&&hasCover&&approved||coverFilter==='porbajar'&&porBajar;row.hidden=!show;const marca=row.querySelector('.cover-review');if(marca&&porBajar)marca.textContent='POR BAJAR'})};$('.catalog-tools').onclick=e=>{const button=e.target.closest('[data-cover-filter]');if(!button)return;coverFilter=button.dataset.coverFilter;renderCatalog()};
// Cartas para imprimir y recortar: abre cartas.html con el código de la
// actividad ya puesto. La vista vive en js/ui/cartas-print.js y lee el pool
// activo por su cuenta, sin crear ningún equipo en la bandeja.
const cartasLink=document.createElement('a');cartasLink.id='printCards';cartasLink.target='_blank';cartasLink.rel='noopener';cartasLink.textContent='Cartas para imprimir';
$('#exportActivity').insertAdjacentElement('afterend',cartasLink);
const baseRenderConCartas=render;render=()=>{baseRenderConCartas();cartasLink.href=`cartas.html?code=${encodeURIComponent(session.code)}`};
$('.delivery-filters').onclick=e=>{if(e.target.dataset.delivery){deliveryFilter=e.target.dataset.delivery;document.querySelectorAll('[data-delivery]').forEach(x=>x.classList.toggle('active',x===e.target));renderDeliveries()}if(e.target.id==='refreshDeliveries')renderDeliveries()};$('#deliveryList').onclick=async e=>{const raw=e.target.dataset.validate||e.target.dataset.return;if(!raw)return;const [encodedTeam,dayId]=raw.split('|'),team=decodeURIComponent(encodedTeam),verdict=e.target.dataset.validate?'validated':'returned';e.target.disabled=true;
try{await setSubmissionStatus(session.code,team,dayId,verdict);log('validation',`${team} · ${activeDays().find(d=>d.id===dayId)?.name}: ${verdict==='validated'?'entrega validada':'entrega devuelta'}.`);persist()}
catch(error){alert(error.message||'No fue posible registrar la validación.')}
finally{e.target.disabled=false;renderDeliveries()}};
addEventListener('storage',e=>{if(e.key?.startsWith(`musicfest:draft:${session.code}:`))renderDeliveries()});addEventListener('musicfest-draft',renderDeliveries);setInterval(()=>{renderDeliveries();renderTeams()},3000);render();renderCatalog();
// Cambios remotos (otra pestaña docente, o el propio servidor tras una
// transacción) se reflejan aquí. Se ignoran mientras haya escrituras locales en
// vuelo para no pisar lo que el docente está editando en este momento.
watchSession(session.code,next=>{if(storeStatus().pendingWrites||!next)return;session=normalizeSession(next);render();renderCatalog()});
document.querySelectorAll('.activity-config input,.artist-creator input,.artist-creator select').forEach(field=>{field.addEventListener('input',saveFormDraft);field.addEventListener('change',saveFormDraft)});restoreFormDraft();
addEventListener('storage',e=>{if(e.key!==`musicfest:session:${session.code}`||!e.newValue)return;const latest=JSON.parse(e.newValue);if(latest.updatedAt&&(!session.updatedAt||latest.updatedAt>session.updatedAt)){session=latest;render();renderCatalog();restoreFormDraft()}});addEventListener('beforeunload',()=>saveFormDraft());
// Exigir nombres únicos es una propiedad de la partida, no del navegador: viaja
// en la actividad y las reglas de Firestore la respetan.
$('#uniqueNames')?.addEventListener('change',e=>{session.teamJoinPolicy=e.target.checked?POLITICAS.UNICA:POLITICAS.ABIERTA;persist()});
$('#teamList')?.addEventListener('click',async e=>{const teamId=e.target?.dataset?.release;if(!teamId)return;
const nombre=e.target.closest('.team-card')?.querySelector('h3')?.textContent||teamId;
if(!confirm(`¿Liberar "${nombre}"? El nombre queda disponible para quien lo tome y el trabajo del equipo se conserva.`))return;
e.target.disabled=true;
try{await releaseTeam(teamId)}catch(problem){alert(problem.message||'No fue posible liberar el equipo.')}
finally{renderTeams()}});
// Abrir o crear una partida. Hasta ahora esto sólo se podía hacer escribiendo
// en localStorage desde la consola del navegador, que no es algo que se le pida
// a un docente cinco minutos antes de una clase.
//
// Cambiar de partida rehace conexión, suscripciones y temporizadores, así que
// en vez de desmontarlo todo a mano se recarga la página: el panel arranca
// leyendo el código de localStorage, que es justo lo que acabamos de cambiar.
let mapaDeCodigos={};
async function renderActivityPicker(){const selector=$('#activityPicker');if(!selector)return;
let partidas=[];try{partidas=await listActivityCodes()}catch(problem){$('#activityMsg').textContent=problem.message||'No fue posible leer las partidas existentes.'}
mapaDeCodigos=Object.fromEntries(partidas.filter(p=>p.activityId).map(p=>[normalizarCodigo(p.code),p.activityId]));
const actual=normalizarCodigo(session.code);
if(!partidas.some(p=>normalizarCodigo(p.code)===actual))partidas=[{code:session.code,activityId:activityId(),updatedAt:session.updatedAt},...partidas];
selector.innerHTML=ordenarPartidas(partidas).map(p=>{const codigo=normalizarCodigo(p.code);
return `<option value="${esc(codigo)}"${codigo===actual?' selected':''}>${esc(codigo)}${codigo===actual?' · abierta':''}</option>`}).join('')}

$('#openActivity')?.addEventListener('click',()=>{const mensaje=$('#activityMsg');mensaje.textContent='';
const {accion,codigo,error}=elegirPartida({seleccionada:$('#activityPicker')?.value,escrita:$('#newActivityCode')?.value,actual:session.code});
if(error){mensaje.textContent=error;return}
if(accion==='quedarse'){mensaje.textContent=`Ya estás en la partida ${codigo}.`;return}
const nueva=!mapaDeCodigos[codigo];
if(nueva&&!confirm(`No existe ninguna partida con el código ${codigo}. ¿Crear una nueva?`))return;
localStorage.setItem('musicfest:admin:last-code',codigo);
location.reload()});

renderActivityPicker();
