import{artists,artwork}from'./data/artists.js';import{days,validate}from'./domain/game.js';import{connect,ensureSession,loadDraft,saveDraft,submitDraft,watchSession,backend}from'./services/store.js';
import{syncedArtwork,releaseInfo as syncedReleaseInfo}from'./data/covers.generated.js';
import{localArtwork}from'./data/covers.local.js';
import{posterModel,posterFilename}from'./domain/poster.js';
import{drawPoster,downloadPoster,fontsReady}from'./ui/poster-canvas.js';
import{ordenarPool,siguienteOrden,flecha,describir,SIN_ORDEN}from'./domain/pool.js';
import{validarCorreos}from'./domain/correo.js';
const $=s=>document.querySelector(s),setSync=text=>{const el=$('#syncText');if(el)el.textContent=text},genreColor={'Pop':'#4ca5ff','Rock':'#078994','Rap':'#f0a51a','Trap Latino':'#ff4d22'};let session,draft,currentDay=0,filter='Todos',query='',orden={...SIN_ORDEN},submitting=false,submitMessage='',submitMessageState='';
const initials=n=>n.split(/\s+/).slice(0,2).map(x=>x[0]).join('').replace('$','A');
const catalogArtists=()=>{const combined=[...artists,...(session?.customArtists||[])],active=session?.activeArtistIds,deleted=session?.deletedArtistIds||[],overrides=session?.artistOverrides||{};const unique=combined.filter((a,i)=>!deleted.includes(a.id)&&combined.findIndex(x=>x.id===a.id)===i).map(a=>({...a,...(overrides[a.id]||{})}));return active?unique.filter(a=>active.includes(a.id)):unique};const catalogArtwork=id=>localArtwork[id]||session?.artwork?.[id]||artwork[id]||syncedArtwork[id];const catalogRelease=id=>session?.releaseInfo?.[id]||syncedReleaseInfo[id];
$('#joinForm').addEventListener('submit',async e=>{e.preventDefault();const code=$('#code').value.trim().toUpperCase(),team=$('#team').value.trim(),campos=[$('#email'),$('#email2')],button=$('#joinForm button'),error=$('#joinError');error.textContent='';campos.forEach(c=>c?.removeAttribute('aria-invalid'));const correos=validarCorreos(campos.map(c=>c?.value||''),{primeroObligatorio:true});if(!correos.ok){error.textContent=correos.error;const roto=campos[correos.indice];roto?.setAttribute('aria-invalid','true');roto?.focus();return}button.disabled=true;button.dataset.label=button.dataset.label||button.innerHTML;button.textContent='Conectando…';
try{await connect({code,role:'student',teamName:team,emails:correos.correos});session=ensureSession(code);draft=loadDraft(code,team);sessionStorage.setItem('musicfest:last',JSON.stringify({code,team,emails:correos.correos}));$('#join').hidden=true;$('#game').hidden=false;$('#teamLabel').textContent=team;$('#sessionLabel').textContent=`PARTIDA ${session.code}`;setSync(backend==='firebase'?'Sincronizado':'Modo local');currentDay=session.mode==='sequential'?session.activeDayIndex:0;watchSession(code,onSession);onSession(session)}
catch(problem){error.textContent=problem.message||'No fue posible entrar a la partida.';button.innerHTML=button.dataset.label}
finally{button.disabled=false}});
function onSession(next){session=next;if(session.days)session.days.forEach((d,i)=>Object.assign(days[i],d));
if(draft&&draft.revision!==session.revision){const fresh=backend==='firebase'?loadDraft(session.code,draft.team):null;
if(fresh&&fresh.revision===session.revision){draft=fresh}
else{const from=session.reopenedFrom??0;days.slice(from).forEach(d=>{if(draft.selections[d.id].length)draft.statuses[d.id]='needs_revalidation'});draft.revision=session.revision;saveDraft(session.code,draft)}}
if(session.mode==='sequential')currentDay=session.activeDayIndex;render()}
addEventListener('musicfest-draft',()=>{if(!session||!draft||backend!=='firebase')return;const fresh=loadDraft(session.code,draft.team);if(JSON.stringify(fresh.statuses)===JSON.stringify(draft.statuses)&&JSON.stringify(fresh.selections)===JSON.stringify(draft.selections))return;draft=fresh;render()});
let pane='pool',posterTimer=null,fontsLoaded=fontsReady();
function currentPoster(){const day=days[currentDay];
return posterModel(draft.selections[day.id],day,catalogArtists(),
{teamName:draft.team,activityName:session.name,revision:draft.revision,status:draft.statuses[day.id]})}
function renderPoster(){if(pane!=='poster'||!session||!draft)return;
clearTimeout(posterTimer);
posterTimer=setTimeout(async()=>{await fontsLoaded;const model=currentPoster();
await drawPoster($('#posterCanvas'),model,{coverOf:catalogArtwork});
$('#posterDownload').disabled=model.empty;
$('#posterAlt').textContent=model.empty?'El cartel está vacío.'
:`Cartel de ${model.day.name}: ${model.artists.map(a=>a.name).join(', ')}. Popularidad ${model.totals.score}.`},120)}
function setPane(next){pane=next;
$('#panePool').hidden=next!=='pool';$('#panePoster').hidden=next!=='poster';
[...$('#poolTabs').children].forEach(b=>{const on=b.dataset.pane===next;b.classList.toggle('active',on);b.setAttribute('aria-selected',String(on))});
renderPoster()}
$('#poolTabs').onclick=e=>{const b=e.target.closest('[data-pane]');if(b)setPane(b.dataset.pane)};
$('#posterDownload').onclick=async()=>{const model=currentPoster();
try{await downloadPoster($('#posterCanvas'),posterFilename(model.teamName,model.day.name));
$('#posterHint').textContent='Cartel descargado.'}
catch(error){$('#posterHint').textContent='No fue posible generar la imagen: '+error.message}};
function render(){if(!session||!draft)return;const active=['active','paused'].includes(session.state);$('#waiting').hidden=active;$('#workspace').hidden=!active;$('#sessionState').textContent=session.state==='lobby'?'Lobby':session.state==='active'?'En curso':session.state==='paused'?'Pausada':'Cerrada';$('#dayTitle').textContent=session.mode==='simultaneous'?'Festival completo':days[currentDay].name;$('#roundLabel').textContent=session.mode==='simultaneous'?'MODO SIMULTÁNEO':`RONDA ${currentDay+1}/3`;renderDays();renderBrief();renderArtists();$('#posterCount').textContent=String(draft.selections[days[currentDay].id].length);renderPoster()}
function renderDays(){const el=$('#daySwitch');el.innerHTML='';if(session.mode==='sequential')return;days.forEach((d,i)=>{const b=document.createElement('button');b.textContent=d.name;b.className=i===currentDay?'active':'';b.onclick=()=>{currentDay=i;render()};el.append(b)})}
function currentIds(){return draft.selections[days[currentDay].id]}
function renderBrief(){const day=days[currentDay],pool=catalogArtists(),result=validate(currentIds(),day,pool),locked=['submitted','closed'].includes(draft.statuses[day.id]);$('#constraints').innerHTML=result.checks.map(([name,ok,value])=>`<div class="constraint ${ok?'ok':''}"><span>${name}</span><b>${value}</b></div>`).join('');$('#score').textContent=String(result.totals.score).padStart(2,'0');const allValid=session.mode==='simultaneous'?days.every(d=>validate(draft.selections[d.id],d,pool).valid):result.valid,hint=$('#submitHint');$('#submit').disabled=!allValid||locked||submitting||session.state!=='active';$('#submit').textContent=submitting?'Confirmando…':locked?'Lineup enviado':session.mode==='simultaneous'?'Enviar festival':'Enviar lineup';hint.textContent=submitMessage|| (draft.statuses[day.id]==='needs_revalidation'?'Este lineup debe validarse y enviarse nuevamente.':!result.valid?'Completa todas las condiciones para enviar.':'');if(submitMessageState)hint.dataset.state=submitMessageState;else delete hint.dataset.state}
function usedElsewhere(id){return days.some((d,i)=>i!==currentDay&&draft.selections[d.id].includes(id))}
function unavailable(id){if(session.mode==='simultaneous')return false;return days.some((d,i)=>i<currentDay&&['submitted','closed'].includes(draft.statuses[d.id])&&draft.selections[d.id].includes(id))}
function renderArtists(){const grid=$('#artistGrid'),locked=['submitted','closed'].includes(draft.statuses[days[currentDay].id]),pool=catalogArtists();grid.innerHTML='';ordenarPool(pool.filter(a=>(filter==='Todos'||a.genre===filter)&&a.name.toLowerCase().includes(query)),orden).forEach(a=>{const selected=currentIds().includes(a.id),other=usedElsewhere(a.id),off=unavailable(a.id),card=document.createElement('button'),number=String(pool.findIndex(x=>x.id===a.id)+1).padStart(3,'0');card.className=`artist ${selected?'selected':''} ${off?'unavailable':''}`;card.dataset.artistId=a.id;card.setAttribute('aria-label',`${selected?'Quitar':'Seleccionar'} ${a.name}`);card.setAttribute('aria-pressed',String(selected));card.style.setProperty('--genre',genreColor[a.genre]);card.disabled=locked||off||session.state!=='active';const cover=catalogArtwork(a.id),art=cover?`<img src="${cover}" alt="Carátula asociada a ${a.name}">`:`<b>${initials(a.name)}</b>`,assignedDay=other?days.find(d=>draft.selections[d.id].includes(a.id)).name:null,status=assignedDay?`ASIGNADO · ${assignedDay}`:selected?'EN TU LINEUP':'DISPONIBLE';card.innerHTML=`<div class="artist-top"><span>${a.genre.toUpperCase()}</span><b>${a.country}</b></div><div class="artist-cover">${art}<small>${cover?'CARÁTULA OFICIAL':'IDENTIDAD VISUAL'}</small></div><div class="artist-head"><div><small>ARTISTA / BANDA</small><h3>${a.name}</h3></div><i>${selected?'✓':'+'}</i></div><div class="artist-data"><span><em>$</em><b>${a.cost}</b><small>COSTO</small></span><span><em>♥</em><b>${a.popularity}</b><small>POPULARIDAD</small></span><span><em>◷</em><b>${a.duration}</b><small>HORAS</small></span></div><footer><span>${status}</span><b>MF · ${number}</b></footer>`;card.onclick=()=>toggleArtist(a.id);grid.append(card)})}
function toggleArtist(id){const dayId=days[currentDay].id,ids=draft.selections[dayId],pos=ids.indexOf(id);if(pos>=0)ids.splice(pos,1);else{if(session.mode==='simultaneous')days.forEach(d=>{draft.selections[d.id]=draft.selections[d.id].filter(x=>x!==id)});ids.push(id)}draft.statuses[dayId]='editable';submitMessage='';submitMessageState='';setSync('Guardando…');saveDraft(session.code,draft);setTimeout(()=>setSync(backend==='firebase'?'Guardado en segundo plano':'Modo local'),500);render()}
$('#search').oninput=e=>{query=e.target.value.toLowerCase();renderArtists()};$('#filters').onclick=e=>{if(!e.target.dataset.genre)return;filter=e.target.dataset.genre;[...$('#filters').children].forEach(x=>x.classList.toggle('active',x===e.target));renderArtists()};
// Ordenar es una lectura del problema: costo contra popularidad contra
// duración. Se aplica sobre el pool ya filtrado, así que convive con el
// filtro de género y con la búsqueda sin que ninguno pise al otro.
function pintarOrden(){const tools=$('#sortTools');if(!tools)return;[...tools.querySelectorAll('[data-sort]')].forEach(b=>{const activo=b.dataset.sort===orden.criterio;b.classList.toggle('active',activo);b.setAttribute('aria-pressed',String(activo));const base=b.dataset.etiqueta||(b.dataset.etiqueta=b.textContent.trim());b.textContent=activo&&b.dataset.sort!=='catalogo'?`${base} ${flecha(orden)}`:base});tools.setAttribute('aria-label',`Ordenar el pool · ${describir(orden)}`)}
$('#sortTools')?.addEventListener('click',e=>{const boton=e.target.closest('[data-sort]');if(!boton)return;orden=siguienteOrden(orden,boton.dataset.sort);pintarOrden();renderArtists()});
pintarOrden();
$('#submit').onclick=()=>{submitMessage='';submitMessageState='';const count=session.mode==='simultaneous'?days.reduce((s,d)=>s+draft.selections[d.id].length,0):currentIds().length;$('#confirmText').textContent=session.mode==='simultaneous'?`Se bloquearán los tres días con ${count} artistas asignados.`:`Se cerrará ${days[currentDay].name} y sus ${count} artistas dejarán de estar disponibles en las rondas siguientes.`;$('#confirm').showModal()};$('#cancelSubmit').onclick=()=>$('#confirm').close();
function mensajeErrorEnvio(error){const code=String(error?.code||'');if(code.includes('permission-denied'))return'Firestore rechazó el envío. Verifica que el docente siga en este mismo día y que la actividad esté en curso.';if(code.includes('unavailable')||code.includes('network'))return'No se pudo confirmar por un problema de conexión. Revisa internet e intenta nuevamente.';return error?.message?`No se pudo confirmar: ${error.message}`:'No se pudo confirmar el envío. Intenta nuevamente.'}
$('#confirmSubmit').onclick=async()=>{if(submitting)return;const targetDays=session.mode==='simultaneous'?days:[days[currentDay]],pool=catalogArtists(),attempt=draft,previous=targetDays.map(d=>({id:d.id,status:attempt.statuses[d.id],submission:attempt.submissions?.[d.id]}));attempt.submissions=attempt.submissions||{};targetDays.forEach(d=>{const result=validate(attempt.selections[d.id],d,pool),dayIndex=days.findIndex(x=>x.id===d.id);attempt.statuses[d.id]='submitted';attempt.submissions[d.id]={dayId:d.id,dayIndex,dayName:d.name,selections:[...attempt.selections[d.id]],totals:result.totals,checks:result.checks,revision:session.revision,validationStatus:'pending',submittedAt:new Date().toISOString()}});submitting=true;submitMessage='Esperando confirmación de Firestore…';submitMessageState='pending';setSync('Confirmando envío…');$('#confirm').close();render();
try{await submitDraft(session.code,attempt);submitMessage='Envío confirmado en Firestore.';submitMessageState='ok';setSync(backend==='firebase'?'Envío confirmado':'Modo local')}
catch(error){draft=attempt;for(const item of previous){draft.statuses[item.id]=item.status||'editable';if(item.submission)draft.submissions[item.id]=item.submission;else delete draft.submissions[item.id]}submitMessage=mensajeErrorEnvio(error);submitMessageState='error';setSync('Envío no confirmado')}
finally{submitting=false;render()}};
// Portada: cada rol ve sólo lo suyo. El docente va directo al panel; al
// estudiante se le despliegan los campos sin cambiar de página.
const showRoles=on=>{$('#joinRoles').hidden=!on;$('#joinForm').hidden=on;if(!on)setTimeout(()=>$('#team').focus(),80)};
$('#roleStudent').onclick=()=>showRoles(false);
$('#roleBack').onclick=()=>{$('#joinError').textContent='';showRoles(true)};
addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#joinForm').hidden)showRoles(true)});
const last=JSON.parse(sessionStorage.getItem('musicfest:last')||'null');
if(last){$('#code').value=last.code;$('#team').value=last.team;const guardados=last.emails||[];[$('#email'),$('#email2')].forEach((campo,i)=>{if(campo&&guardados[i])campo.value=guardados[i]});showRoles(false)}
