import{store,enabled,normalizeCode}from'./firebase.js?v=8';
document.head.insertAdjacentHTML('beforeend','<style>.admin-auth{margin:-20px 0 28px;background:var(--ink);color:white;border:0;padding:12px 18px;text-transform:uppercase;letter-spacing:.08em}</style>');
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="validation.css">');
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="round-objective.css?v=8">');
const $=s=>document.querySelector(s),D=window.ODYSSEY_DATA;const defaultIds=()=>['troy','ithaca',...D.places.filter(p=>!p.required).sort((a,b)=>a.order-b.order).slice(0,8).map(p=>p.id)];let code=$('#activityCode').value,active=false,round=1,objectiveMetric='distance',activeNodeIds=defaultIds(),nodeCount=activeNodeIds.length,nodePositions={},attempts=[],optimalResult=null,optimalTimer=0,optimalWorker=null,stopWatch=()=>{},stopAttempts=()=>{};
const validMetric=value=>D.metrics[value]?value:'distance';
const locationPresets={all:D.places.map(p=>p.id),simple:['troy','ithaca','lotophagi','lamos','cimmerians','cyclopes'],medium:['troy','ithaca','lotophagi','lamos','cimmerians','cyclopes','sirens','thrinacia','aeaea'],nolan:['troy','ithaca','cyclopes','lamos','aeaea','cimmerians','sirens','scylla','charybdis','thrinacia','ogygia'],clear:['troy','ithaca']};
let adminReady=!enabled;function setAdminView(unlocked){$('#adminGate').hidden=unlocked;$('#adminPanel').hidden=!unlocked}setAdminView(adminReady);async function ensureAdmin(){if(!adminReady){await store.adminLogin();adminReady=true;setAdminView(true);stopAttempts();stopAttempts=store.watchAttempts(code,x=>{attempts=x;renderRecords();renderOptimal()})}}
function render(){$('#status').textContent=active?`“${code}” está navegando`:`“${code}” está en puerto`;$('#toggle').textContent=active?'Pausar experiencia':'Iniciar experiencia';nodeCount=activeNodeIds.length;$('#nodeOutput').textContent=nodeCount;document.querySelectorAll('[data-round]').forEach(b=>b.classList.toggle('on',+b.dataset.round===round));document.querySelectorAll('[data-objective]').forEach(b=>b.classList.toggle('on',b.dataset.objective===objectiveMetric));$('#adminMsg').textContent=enabled?'Firebase conectado · el acceso docente requiere permiso admin':'Modo demo local · abra otra pestaña para probar como alumno';renderLocationChoices();renderPositionEditor()}
function fallbackIds(count=10){return['troy','ithaca',...D.places.filter(p=>!p.required).sort((a,b)=>a.order-b.order).slice(0,Math.max(3,count-2)).map(p=>p.id)]}
async function selectActivity(nextCode){stopWatch();stopAttempts();code=nextCode.trim();const found=await store.load(code);active=!!found?.active;round=found?.round||1;objectiveMetric=validMetric(found?.objectiveMetric);activeNodeIds=found?.activeNodeIds||fallbackIds(found?.nodeCount);nodeCount=activeNodeIds.length;nodePositions=found?.nodePositions||{};stopWatch=store.watchExp(code,x=>{if(x){active=!!x.active;round=x.round||1;objectiveMetric=validMetric(x.objectiveMetric);activeNodeIds=x.activeNodeIds||fallbackIds(x.nodeCount);nodeCount=activeNodeIds.length;nodePositions=x.nodePositions||{};render();scheduleOptimal()}});attempts=[];stopAttempts=adminReady?store.watchAttempts(code,x=>{attempts=x;renderRecords();renderOptimal()}):()=>{};render();scheduleOptimal()}
const pointOf=p=>nodePositions[p.id]||{x:p.x,y:p.y};
function activeIds(){return new Set(activeNodeIds)}
function sameSelection(a,b){const left=new Set(a),right=new Set(b);return left.size===right.size&&[...left].every(id=>right.has(id))}
function updatePresetState(){document.querySelectorAll('[data-location-preset]').forEach(button=>button.classList.toggle('on',sameSelection(activeNodeIds,locationPresets[button.dataset.locationPreset])))}
function applyLocationPreset(name){const selected=new Set(locationPresets[name]||locationPresets.clear);activeNodeIds=D.places.filter(p=>selected.has(p.id)).map(p=>p.id);nodeCount=activeNodeIds.length;$('#nodeOutput').textContent=nodeCount;renderLocationChoices();renderPositionEditor();scheduleOptimal();$('#adminMsg').textContent=`Selección ${name==='clear'?'limpia':buttonLabel(name)} aplicada · pulse Guardar configuración para conservarla`}
function buttonLabel(name){return({all:'Todas',simple:'Simple',medium:'Media',nolan:'Nolan'})[name]||name}
function renderLocationChoices(){const chosen=activeIds();$('#locationChoices').innerHTML=D.places.map(p=>`<label class="location-choice ${p.required?'locked':''}"><input type="checkbox" data-place="${p.id}" ${chosen.has(p.id)?'checked':''} ${p.required?'disabled':''}>${p.name}</label>`).join('');document.querySelectorAll('[data-place]:not(:disabled)').forEach(input=>input.onchange=()=>{const next=new Set(activeNodeIds);input.checked?next.add(input.dataset.place):next.delete(input.dataset.place);activeNodeIds=D.places.filter(p=>next.has(p.id)).map(p=>p.id);nodeCount=activeNodeIds.length;$('#nodeOutput').textContent=nodeCount;updatePresetState();renderPositionEditor();scheduleOptimal()});updatePresetState()}
function renderPositionEditor(){const activeSet=activeIds();$('#positionMap').innerHTML=D.places.map((p,i)=>{const pos=pointOf(p);return`<button class="position-dot ${activeSet.has(p.id)?'':'inactive'}" data-id="${p.id}" data-name="${p.name}" title="${p.name}" style="left:${pos.x}%;top:${pos.y}%">${i+1}</button>`}).join('');document.querySelectorAll('.position-dot').forEach(dot=>{dot.onpointerdown=e=>startDrag(e,dot)})}
const safe=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const placeName=id=>D.places.find(p=>p.id===id)?.name||id;
const attemptDate=value=>{const d=value?.toDate?value.toDate():value?new Date(value):null;return d&&!Number.isNaN(d.valueOf())?d:null};
function renderRecords(){const body=$('#recordsBody'),validated=attempts.filter(a=>a.validated===true).length;$('#recordsSummary').textContent=`${attempts.length} ${attempts.length===1?'entrega':'entregas'} · ${validated} validadas · ${code}`;if(!attempts.length){body.innerHTML='<tr><td colspan="8" class="empty-records">Todavía no hay entregas para esta actividad.</td></tr>';return}body.innerHTML=attempts.map(a=>{const date=attemptDate(a.createdAt),route=(a.route||[]).map(placeName).join(' → '),metric=D.metrics[a.metric]?.[0]||a.metric,isValid=a.validated===true;return`<tr class="${isValid?'validated-row':'pending-row'}"><td><b>${safe(a.teamName||a.teamId||'Equipo')}</b></td><td>${safe(a.round||'—')}</td><td>${safe(metric)}</td><td class="route-cell">${safe(route)}</td><td class="score-cell">${safe(a.score)}</td><td>${date?safe(date.toLocaleString('es-CL')):'—'}</td><td><span class="validation-badge ${isValid?'valid':'pending'}">${isValid?'Validado':'Pendiente'}</span></td><td class="record-actions"><button class="validate-record ${isValid?'remove-validation':''}" data-validate-attempt="${safe(a.id)}" data-next-validation="${!isValid}">${isValid?'Retirar validación':'Validar'}</button><button class="delete-record" data-delete-attempt="${safe(a.id)}">Eliminar</button></td></tr>`}).join('');document.querySelectorAll('[data-validate-attempt]').forEach(button=>button.onclick=async()=>{await ensureAdmin();await store.validateAttempt(code,button.dataset.validateAttempt,button.dataset.nextValidation==='true')});document.querySelectorAll('[data-delete-attempt]').forEach(button=>button.onclick=async()=>{const item=attempts.find(a=>a.id===button.dataset.deleteAttempt);if(!confirm(`¿Eliminar la entrega de ${item?.teamName||item?.teamId||'este equipo'}? Esta acción no se puede deshacer.`))return;await ensureAdmin();await store.deleteAttempt(code,button.dataset.deleteAttempt)})}
function scheduleOptimal(){clearTimeout(optimalTimer);optimalResult=null;$('#optimalValue').textContent='…';$('#optimalRoute').textContent='Calculando solución exacta…';$('#optimalMeta').textContent='';optimalTimer=setTimeout(calculateOptimal,180)}
function calculateOptimal(){optimalWorker?.terminate();optimalWorker=new Worker('optimal-worker.js?v=2');const started=performance.now(),nodes=D.places.filter(p=>activeNodeIds.includes(p.id)).map(p=>p.id),matrix=D.rounds[round-1].matrices[objectiveMetric];$('#optimalContext').textContent=`Ronda ${round} · ${D.metrics[objectiveMetric][0]} · ${nodes.length} locaciones`;optimalWorker.onmessage=e=>{if(e.data.error){$('#optimalValue').textContent='Sin ruta';$('#optimalRoute').textContent=e.data.error;return}optimalResult={...e.data,elapsed:performance.now()-started};renderOptimal()};optimalWorker.onerror=()=>{$('#optimalValue').textContent='Error';$('#optimalRoute').textContent='No fue posible calcular el óptimo.'};optimalWorker.postMessage({nodes,matrix})}
function renderOptimal(){if(!optimalResult)return;const unit=D.metrics[objectiveMetric][1],bestTeam=attempts.filter(a=>a.validated===true&&a.round===round&&a.metric===objectiveMetric).sort((a,b)=>a.score-b.score)[0];$('#optimalValue').textContent=optimalResult.value;$('#optimalUnit').textContent=unit;$('#optimalRoute').textContent=optimalResult.route.map(placeName).join(' → ');const comparison=bestTeam?` · Mejor equipo: ${bestTeam.score} ${unit} · Brecha: ${+(bestTeam.score-optimalResult.value).toFixed(1)} ${unit}`:'';$('#optimalMeta').textContent=`Óptimo certificado · ${optimalResult.method} · ${Math.round(optimalResult.elapsed)} ms${comparison}`}
function openPrintSheet(mode){if(mode==='teacher'&&!optimalResult){$('#adminMsg').textContent='Espere a que termine el cálculo óptimo antes de imprimir la pauta docente.';return}const payload={code:$('#activityCode').value.trim()||code,round,metric:objectiveMetric,activeNodeIds:[...activeNodeIds],mode,optimal:mode==='teacher'?optimalResult:null,createdAt:new Date().toISOString()};localStorage.setItem('odisea:print-sheet',JSON.stringify(payload));window.open(`print.html?mode=${mode}`,'_blank')}
function startDrag(event,dot){event.preventDefault();dot.setPointerCapture(event.pointerId);document.querySelectorAll('.position-dot').forEach(x=>x.classList.remove('selected'));dot.classList.add('selected');const move=e=>{const box=$('#positionMap').getBoundingClientRect(),x=Math.max(0,Math.min(100,(e.clientX-box.left)/box.width*100)),y=Math.max(0,Math.min(100,(e.clientY-box.top)/box.height*100));nodePositions[dot.dataset.id]={x:+x.toFixed(2),y:+y.toFixed(2)};dot.style.left=x+'%';dot.style.top=y+'%';$('#selectedPoint').textContent=`${dot.dataset.name} · x ${x.toFixed(1)}% · y ${y.toFixed(1)}%`};const stop=()=>{dot.removeEventListener('pointermove',move);dot.removeEventListener('pointerup',stop);dot.removeEventListener('pointercancel',stop)};dot.addEventListener('pointermove',move);dot.addEventListener('pointerup',stop);dot.addEventListener('pointercancel',stop)}
$('#save').onclick=async()=>{const next=$('#activityCode').value.trim();if(!next)return;await ensureAdmin();code=next;nodeCount=activeNodeIds.length;await store.control(code,{code,activityId:normalizeCode(code),activeNodeIds,nodeCount,round,objectiveMetric,active});await selectActivity(code);$('#adminMsg').textContent=`Configuración guardada · código de acceso: ${code}`};
$('#toggle').onclick=async()=>{code=$('#activityCode').value.trim();if(!code)return;await ensureAdmin();nodeCount=activeNodeIds.length;active=!active;await store.control(code,{code,activityId:normalizeCode(code),active,activeNodeIds,nodeCount,round,objectiveMetric});render()};
document.querySelectorAll('[data-round]').forEach(b=>b.onclick=async()=>{await ensureAdmin();round=+b.dataset.round;await store.control(code,{round});render();scheduleOptimal()});
document.querySelectorAll('[data-objective]').forEach(b=>b.onclick=async()=>{await ensureAdmin();objectiveMetric=b.dataset.objective;await store.control(code,{objectiveMetric});render();scheduleOptimal()});
document.querySelectorAll('[data-location-preset]').forEach(button=>button.onclick=()=>applyLocationPreset(button.dataset.locationPreset));
document.querySelectorAll('[data-print-sheet]').forEach(button=>button.onclick=()=>openPrintSheet(button.dataset.printSheet));
$('#calculateOptimal').onclick=calculateOptimal;
$('#resetPositions').onclick=()=>{nodePositions={};renderPositionEditor();$('#selectedPoint').textContent='Posiciones originales restablecidas (aún sin guardar)'};
$('#savePositions').onclick=async()=>{await ensureAdmin();await store.control(code,{nodePositions});$('#selectedPoint').textContent='Posiciones guardadas para esta actividad ✓'};
$('#adminAuth').onclick=async()=>{const button=$('#adminAuth');button.disabled=true;$('#adminGateMsg').textContent='Verificando cuenta…';try{await ensureAdmin();await selectActivity($('#activityCode').value.trim())}catch(error){$('#adminGateMsg').textContent=error.message||'No fue posible validar esta cuenta.';button.disabled=false}};
function loadXlsx(){if(window.XLSX)return Promise.resolve(window.XLSX);return new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://cdn.sheetjs.com/xlsx-0.20.3/package/dist/xlsx.full.min.js';script.onload=()=>resolve(window.XLSX);script.onerror=()=>reject(new Error('No fue posible cargar el generador de Excel.'));document.head.appendChild(script)})}
$('#exportExcel').onclick=async()=>{if(!attempts.length){$('#adminMsg').textContent='No hay registros para exportar en esta actividad.';return}try{const XLSX=await loadXlsx(),rows=attempts.map(a=>{const date=attemptDate(a.createdAt);return{'Sesión':code,'Equipo':a.teamName||a.teamId||'Equipo','Métrica':D.metrics[a.metric]?.[0]||a.metric,'Ruta':(a.route||[]).map(placeName).join(' → '),'Valor función objetivo':Number(a.score),'Ronda':Number(a.round)||'','Fecha':date||'','Estado':a.validated===true?'Validado':'Pendiente'}}),sheet=XLSX.utils.json_to_sheet(rows),book=XLSX.utils.book_new();sheet['!cols']=[{wch:22},{wch:24},{wch:16},{wch:70},{wch:24},{wch:12},{wch:22},{wch:14}];sheet['!autofilter']={ref:`A1:H${rows.length+1}`};XLSX.utils.book_append_sheet(book,sheet,'Resultados');book.Props={Title:`Resultados ${code}`,Subject:'Odisea Óptima',Author:'Odisea Óptima'};XLSX.writeFile(book,`resultados_${normalizeCode(code)}.xlsx`,{compression:true});$('#adminMsg').textContent=`Excel exportado · ${attempts.length} registros`}catch(error){$('#adminMsg').textContent=error.message}};
selectActivity(code);
