import{store,enabled,normalizeCode}from'./firebase.js?v=9';
document.head.insertAdjacentHTML('beforeend','<style>.admin-auth{margin:-20px 0 28px;background:var(--ink);color:white;border:0;padding:12px 18px;text-transform:uppercase;letter-spacing:.08em}</style>');
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="validation.css">');
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="round-objective.css?v=8">');
const $=s=>document.querySelector(s),D=window.ODYSSEY_DATA;const defaultIds=()=>['troy','ithaca',...D.places.filter(p=>!p.required).sort((a,b)=>a.order-b.order).slice(0,8).map(p=>p.id)];let code=$('#activityCode').value,active=false,round=1,objectiveMetric='distance',activeNodeIds=defaultIds(),nodeCount=activeNodeIds.length,nodePositions={},attempts=[],optimalResult=null,optimalTimer=0,optimalWorker=null,stopWatch=()=>{},stopAttempts=()=>{},refreshTimer=0,draftDirty=false,publishedConfigurationKey='';
const validMetric=value=>D.metrics[value]?value:'distance';
const locationPresets={all:D.places.map(p=>p.id),simple:['troy','ithaca','lotophagi','lamos','cimmerians','cyclopes'],medium:['troy','ithaca','lotophagi','lamos','cimmerians','cyclopes','sirens','thrinacia','aeaea'],nolan:['troy','ithaca','cyclopes','lamos','aeaea','cimmerians','sirens','scylla','charybdis','thrinacia','ogygia'],clear:['troy','ithaca']};
let adminReady=!enabled;function setAdminView(unlocked){$('#adminGate').hidden=unlocked;$('#adminPanel').hidden=!unlocked}setAdminView(adminReady);async function ensureAdmin(){if(!adminReady){await store.adminLogin();adminReady=true;setAdminView(true);stopAttempts();stopAttempts=store.watchAttempts(code,x=>{attempts=x;renderRecords();renderOptimal()})}}
function render(){$('#status').textContent=active?`“${code}” está navegando`:`“${code}” está en puerto`;$('#toggle').textContent=active?'Pausar experiencia':'Iniciar experiencia';nodeCount=activeNodeIds.length;$('#nodeOutput').textContent=nodeCount;document.querySelectorAll('[data-round]').forEach(b=>b.classList.toggle('on',+b.dataset.round===round));document.querySelectorAll('[data-objective]').forEach(b=>b.classList.toggle('on',b.dataset.objective===objectiveMetric));$('#adminMsg').textContent=enabled?'Firebase conectado · acceso docente verificado':'Modo demo local · abra otra pestaña para probar como alumno';renderLocationChoices();renderPositionEditor();renderConfigurationSummary();renderRecords()}
function setDraftDirty(value=true){draftDirty=value;$('#draftStatus').textContent=value?'Cambios sin publicar':'Configuración publicada';$('#draftHelp').textContent=value?'Los estudiantes conservan la última configuración guardada hasta que pulses Guardar configuración.':'Los estudiantes ven esta configuración.';$('#save').classList.toggle('has-changes',value)}
$('#exportExcel').insertAdjacentHTML('beforebegin','<button id="refreshRecords" class="refresh-records" type="button">↻ Actualizar ahora</button>');
$('#recordsSummary').insertAdjacentHTML('afterend','<small id="recordsRefreshStatus" class="records-refresh-status">Esperando resultados…</small>');
function showRefreshStatus(prefix){const now=new Date().toLocaleTimeString('es-CL',{hour:'2-digit',minute:'2-digit',second:'2-digit'});$('#recordsRefreshStatus').textContent=`${prefix} · ${now}`}
async function refreshAttempts(manual=true){if(!adminReady)return;const button=$('#refreshRecords');if(manual){button.disabled=true;button.textContent='Actualizando…'}try{attempts=await store.listAttempts(code);renderRecords();renderOptimal();showRefreshStatus(manual?'Actualizado manualmente':'Comprobación automática')}catch(error){showRefreshStatus('No se pudo actualizar');if(manual)$('#adminMsg').textContent=error.message||'No fue posible actualizar la bitácora.'}finally{if(manual){button.disabled=false;button.textContent='↻ Actualizar ahora'}}}
function fallbackIds(count=10){return['troy','ithaca',...D.places.filter(p=>!p.required).sort((a,b)=>a.order-b.order).slice(0,Math.max(3,count-2)).map(p=>p.id)]}
async function selectActivity(nextCode){stopWatch();stopAttempts();clearInterval(refreshTimer);code=nextCode.trim();const found=await store.load(code);active=!!found?.active;round=found?.round||1;objectiveMetric=validMetric(found?.objectiveMetric);activeNodeIds=found?.activeNodeIds||fallbackIds(found?.nodeCount);nodeCount=activeNodeIds.length;nodePositions=found?.nodePositions||{};publishedConfigurationKey=found?.configurationKey||D.configurationKey(round,objectiveMetric,activeNodeIds);draftDirty=false;stopWatch=store.watchExp(code,x=>{if(x){active=!!x.active;nodePositions=x.nodePositions||{};publishedConfigurationKey=x.configurationKey||publishedConfigurationKey;if(!draftDirty){round=x.round||1;objectiveMetric=validMetric(x.objectiveMetric);activeNodeIds=x.activeNodeIds||fallbackIds(x.nodeCount);nodeCount=activeNodeIds.length}render();setDraftDirty(draftDirty);scheduleOptimal()}});attempts=[];stopAttempts=adminReady?store.watchAttempts(code,x=>{attempts=x;renderRecords();renderOptimal();showRefreshStatus('Actualización en vivo')}):()=>{};if(adminReady)refreshTimer=setInterval(()=>refreshAttempts(false),10000);render();setDraftDirty(false);scheduleOptimal()}
const pointOf=p=>nodePositions[p.id]||{x:p.x,y:p.y};
function activeIds(){return new Set(activeNodeIds)}
const draftConfigurationKey=()=>D.configurationKey(round,objectiveMetric,activeNodeIds),currentConfigurationKey=()=>draftDirty&&publishedConfigurationKey?publishedConfigurationKey:draftConfigurationKey(),configurationPayload=()=>({activeNodeIds:[...activeNodeIds],nodeCount:activeNodeIds.length,round,objectiveMetric,configurationKey:draftConfigurationKey()});
function configurationLabel(item={}){if(item.configurationName)return item.configurationName;const roundInfo=D.rounds[(Number(item.round)||1)-1],metricInfo=D.metrics[item.metric||item.objectiveMetric];return`${roundInfo?.title||`Ronda ${item.round||'—'}`} · ${metricInfo?.[0]||item.metric||item.objectiveMetric||'Objetivo desconocido'} · ${item.activeNodeIds?.length||item.nodeCount||'?'} lugares`}
function renderConfigurationSummary(){$('#configurationActivity').textContent=$('#activityCode').value.trim()||code||'—';$('#configurationRound').textContent=D.rounds[round-1]?.title||`Ronda ${round}`;$('#configurationMetric').textContent=D.metrics[objectiveMetric]?.[0]||objectiveMetric;$('#configurationNodes').textContent=`${activeNodeIds.length} lugares`;$('#configurationPlaces').textContent=activeNodeIds.map(placeName).join(' · ')}
function sameSelection(a,b){const left=new Set(a),right=new Set(b);return left.size===right.size&&[...left].every(id=>right.has(id))}
function updatePresetState(){document.querySelectorAll('[data-location-preset]').forEach(button=>button.classList.toggle('on',sameSelection(activeNodeIds,locationPresets[button.dataset.locationPreset])))}
function applyLocationPreset(name){const selected=new Set(locationPresets[name]||locationPresets.clear);activeNodeIds=D.places.filter(p=>selected.has(p.id)).map(p=>p.id);nodeCount=activeNodeIds.length;setDraftDirty();$('#nodeOutput').textContent=nodeCount;renderLocationChoices();renderPositionEditor();renderConfigurationSummary();renderRecords();scheduleOptimal();$('#adminMsg').textContent=`Selección ${name==='clear'?'limpia':buttonLabel(name)} aplicada · pulse Guardar configuración para publicarla`}
function buttonLabel(name){return({all:'Todas',simple:'Simple',medium:'Media',nolan:'Nolan'})[name]||name}
function renderLocationChoices(){const chosen=activeIds();$('#locationChoices').innerHTML=D.places.map(p=>`<label class="location-choice ${p.required?'locked':''}"><input type="checkbox" data-place="${p.id}" ${chosen.has(p.id)?'checked':''} ${p.required?'disabled':''}>${p.name}</label>`).join('');document.querySelectorAll('[data-place]:not(:disabled)').forEach(input=>input.onchange=()=>{const next=new Set(activeNodeIds);input.checked?next.add(input.dataset.place):next.delete(input.dataset.place);activeNodeIds=D.places.filter(p=>next.has(p.id)).map(p=>p.id);nodeCount=activeNodeIds.length;setDraftDirty();$('#nodeOutput').textContent=nodeCount;updatePresetState();renderPositionEditor();renderConfigurationSummary();renderRecords();scheduleOptimal()});updatePresetState()}
function renderPositionEditor(){const activeSet=activeIds();$('#positionMap').innerHTML=D.places.map((p,i)=>{const pos=pointOf(p);return`<button class="position-dot ${activeSet.has(p.id)?'':'inactive'}" data-id="${p.id}" data-name="${p.name}" title="${p.name}" style="left:${pos.x}%;top:${pos.y}%">${i+1}</button>`}).join('');document.querySelectorAll('.position-dot').forEach(dot=>{dot.onpointerdown=e=>startDrag(e,dot)})}
const safe=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const placeName=id=>D.places.find(p=>p.id===id)?.name||id;
const attemptDate=value=>{const d=value?.toDate?value.toDate():value?new Date(value):null;return d&&!Number.isNaN(d.valueOf())?d:null};
const formatDuration=value=>{if(!Number.isFinite(Number(value)))return'—';const seconds=Math.max(0,Math.round(Number(value)/1000)),minutes=Math.floor(seconds/60);return minutes?`${minutes} min ${String(seconds%60).padStart(2,'0')} s`:`${seconds} s`};
function renderRecords(){const body=$('#recordsBody'),scope=$('#recordsScope').value,key=currentConfigurationKey(),visible=scope==='current'?attempts.filter(a=>a.configurationKey===key):attempts,validated=visible.filter(a=>a.validated===true).length;$('#recordsSummary').textContent=`${visible.length} ${visible.length===1?'entrega':'entregas'} · ${validated} validadas · ${scope==='current'?'configuración activa':'historial completo'} · ${code}`;if(!visible.length){body.innerHTML=`<tr><td colspan="8" class="empty-records">${scope==='current'?'Todavía no hay entregas para esta configuración.':'Todavía no hay entregas para esta actividad.'}</td></tr>`;return}body.innerHTML=visible.map(a=>{const date=attemptDate(a.createdAt),route=(a.route||[]).map(placeName).join(' → '),isValid=a.validated===true,legacy=!a.configurationKey;return`<tr class="${isValid?'validated-row':'pending-row'}"><td><b>${safe(a.teamName||a.teamId||'Equipo')}</b></td><td class="configuration-cell"><b>${safe(configurationLabel(a))}</b><small>${legacy?'Registro histórico sin localidades exactas':safe((a.activeNodeIds||[]).map(placeName).join(' · '))}</small></td><td class="route-cell">${safe(route)}</td><td class="score-cell">${safe(a.score)} <small>${safe(D.metrics[a.metric]?.[1]||'')}</small></td><td class="duration-cell">${safe(formatDuration(a.durationMs))}</td><td>${date?safe(date.toLocaleString('es-CL')):'—'}</td><td><span class="validation-badge ${isValid?'valid':'pending'}">${isValid?'Validado':'Pendiente'}</span></td><td class="record-actions"><button class="validate-record ${isValid?'remove-validation':''}" data-validate-attempt="${safe(a.id)}" data-next-validation="${!isValid}">${isValid?'Retirar validación':'Validar'}</button><button class="delete-record" data-delete-attempt="${safe(a.id)}">Eliminar</button></td></tr>`}).join('');document.querySelectorAll('[data-validate-attempt]').forEach(button=>button.onclick=async()=>{await ensureAdmin();await store.validateAttempt(code,button.dataset.validateAttempt,button.dataset.nextValidation==='true')});document.querySelectorAll('[data-delete-attempt]').forEach(button=>button.onclick=async()=>{const item=attempts.find(a=>a.id===button.dataset.deleteAttempt);if(!confirm(`¿Eliminar la entrega de ${item?.teamName||item?.teamId||'este equipo'}? Esta acción no se puede deshacer.`))return;await ensureAdmin();await store.deleteAttempt(code,button.dataset.deleteAttempt)})}
function scheduleOptimal(){clearTimeout(optimalTimer);optimalResult=null;$('#optimalValue').textContent='…';$('#optimalRoute').textContent='Calculando solución exacta…';$('#optimalMeta').textContent='';optimalTimer=setTimeout(calculateOptimal,180)}
function calculateOptimal(){optimalWorker?.terminate();optimalWorker=new Worker('optimal-worker.js?v=2');const started=performance.now(),nodes=D.places.filter(p=>activeNodeIds.includes(p.id)).map(p=>p.id),matrix=D.rounds[round-1].matrices[objectiveMetric];$('#optimalContext').textContent=`Ronda ${round} · ${D.metrics[objectiveMetric][0]} · ${nodes.length} locaciones`;optimalWorker.onmessage=e=>{if(e.data.error){$('#optimalValue').textContent='Sin ruta';$('#optimalRoute').textContent=e.data.error;return}optimalResult={...e.data,elapsed:performance.now()-started};renderOptimal()};optimalWorker.onerror=()=>{$('#optimalValue').textContent='Error';$('#optimalRoute').textContent='No fue posible calcular el óptimo.'};optimalWorker.postMessage({nodes,matrix})}
function renderOptimal(){if(!optimalResult)return;const unit=D.metrics[objectiveMetric][1],key=currentConfigurationKey(),bestTeam=attempts.filter(a=>a.validated===true&&a.configurationKey===key).sort((a,b)=>a.score-b.score)[0];$('#optimalValue').textContent=optimalResult.value;$('#optimalUnit').textContent=unit;$('#optimalRoute').textContent=optimalResult.route.map(placeName).join(' → ');const comparison=bestTeam?` · Mejor equipo: ${bestTeam.score} ${unit} · Brecha: ${+(bestTeam.score-optimalResult.value).toFixed(1)} ${unit}`:'';$('#optimalMeta').textContent=`Óptimo certificado · ${optimalResult.method} · ${Math.round(optimalResult.elapsed)} ms${comparison}`}
function openPrintSheet(mode){if(mode==='teacher'&&!optimalResult){$('#adminMsg').textContent='Espere a que termine el cálculo óptimo antes de imprimir la pauta docente.';return}const payload={code:$('#activityCode').value.trim()||code,round,metric:objectiveMetric,activeNodeIds:[...activeNodeIds],mode,optimal:mode==='teacher'?optimalResult:null,createdAt:new Date().toISOString()};localStorage.setItem('odisea:print-sheet',JSON.stringify(payload));window.open(`print.html?mode=${mode}`,'_blank')}
function startDrag(event,dot){event.preventDefault();dot.setPointerCapture(event.pointerId);document.querySelectorAll('.position-dot').forEach(x=>x.classList.remove('selected'));dot.classList.add('selected');const move=e=>{const box=$('#positionMap').getBoundingClientRect(),x=Math.max(0,Math.min(100,(e.clientX-box.left)/box.width*100)),y=Math.max(0,Math.min(100,(e.clientY-box.top)/box.height*100));nodePositions[dot.dataset.id]={x:+x.toFixed(2),y:+y.toFixed(2)};dot.style.left=x+'%';dot.style.top=y+'%';$('#selectedPoint').textContent=`${dot.dataset.name} · x ${x.toFixed(1)}% · y ${y.toFixed(1)}%`};const stop=()=>{dot.removeEventListener('pointermove',move);dot.removeEventListener('pointerup',stop);dot.removeEventListener('pointercancel',stop)};dot.addEventListener('pointermove',move);dot.addEventListener('pointerup',stop);dot.addEventListener('pointercancel',stop)}
$('#save').onclick=async()=>{const next=$('#activityCode').value.trim();if(!next)return;await ensureAdmin();code=next;await store.control(code,{code,activityId:normalizeCode(code),...configurationPayload(),active});draftDirty=false;await selectActivity(code);$('#adminMsg').textContent=`Configuración publicada · código de acceso: ${code}`};
$('#toggle').onclick=async()=>{code=$('#activityCode').value.trim();if(!code)return;await ensureAdmin();active=!active;await store.control(code,{code,activityId:normalizeCode(code),active});render();setDraftDirty(draftDirty)};
document.querySelectorAll('[data-round]').forEach(b=>b.onclick=()=>{round=+b.dataset.round;setDraftDirty();render();setDraftDirty(true);scheduleOptimal()});
document.querySelectorAll('[data-objective]').forEach(b=>b.onclick=()=>{objectiveMetric=b.dataset.objective;setDraftDirty();render();setDraftDirty(true);scheduleOptimal()});
document.querySelectorAll('[data-location-preset]').forEach(button=>button.onclick=()=>applyLocationPreset(button.dataset.locationPreset));
document.querySelectorAll('[data-print-sheet]').forEach(button=>button.onclick=()=>openPrintSheet(button.dataset.printSheet));
$('#calculateOptimal').onclick=calculateOptimal;
$('#activityCode').oninput=renderConfigurationSummary;
$('#recordsScope').onchange=()=>{renderRecords();renderOptimal()};
$('#refreshRecords').onclick=()=>refreshAttempts(true);
$('#resetPositions').onclick=()=>{nodePositions={};renderPositionEditor();$('#selectedPoint').textContent='Posiciones originales restablecidas (aún sin guardar)'};
$('#savePositions').onclick=async()=>{await ensureAdmin();await store.control(code,{nodePositions});$('#selectedPoint').textContent='Posiciones guardadas para esta actividad ✓'};
$('#adminAuth').onclick=async()=>{const button=$('#adminAuth');button.disabled=true;$('#adminGateMsg').textContent='Verificando cuenta…';try{await ensureAdmin();await selectActivity($('#activityCode').value.trim())}catch(error){$('#adminGateMsg').textContent=error.message||'No fue posible validar esta cuenta.';button.disabled=false}};
function loadXlsx(){if(window.XLSX)return Promise.resolve(window.XLSX);return new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://cdn.sheetjs.com/xlsx-0.20.3/package/dist/xlsx.full.min.js';script.onload=()=>resolve(window.XLSX);script.onerror=()=>reject(new Error('No fue posible cargar el generador de Excel.'));document.head.appendChild(script)})}
$('#exportExcel').onclick=async()=>{const scope=$('#recordsScope').value,key=currentConfigurationKey(),selected=scope==='current'?attempts.filter(a=>a.configurationKey===key):attempts;if(!selected.length){$('#adminMsg').textContent='No hay registros para exportar en esta vista.';return}try{const XLSX=await loadXlsx(),rows=selected.map(a=>{const date=attemptDate(a.createdAt);return{'Actividad':code,'Equipo':a.teamName||a.teamId||'Equipo','Configuración':configurationLabel(a),'ID configuración':a.configurationKey||'Histórica sin detalle','Localidades':(a.activeNodeIds||[]).map(placeName).join(' · '),'Ruta':(a.route||[]).map(placeName).join(' → '),'Métrica':D.metrics[a.metric]?.[0]||a.metric,'Valor función objetivo':Number(a.score),'Tiempo de resolución':formatDuration(a.durationMs),'Tiempo (segundos)':Number.isFinite(Number(a.durationMs))?Number(a.durationMs)/1000:'','Ronda':D.rounds[(Number(a.round)||1)-1]?.title||a.round||'','Fecha':date||'','Estado':a.validated===true?'Validado':'Pendiente'}}),sheet=XLSX.utils.json_to_sheet(rows),book=XLSX.utils.book_new();sheet['!cols']=[{wch:22},{wch:24},{wch:38},{wch:65},{wch:70},{wch:70},{wch:18},{wch:24},{wch:22},{wch:18},{wch:24},{wch:22},{wch:14}];sheet['!autofilter']={ref:`A1:M${rows.length+1}`};XLSX.utils.book_append_sheet(book,sheet,'Resultados');book.Props={Title:`Resultados ${code}`,Subject:'La Odisea',Author:'La Odisea'};XLSX.writeFile(book,`resultados_${normalizeCode(code)}.xlsx`,{compression:true});$('#adminMsg').textContent=`Excel exportado · ${selected.length} registros`}catch(error){$('#adminMsg').textContent=error.message}};
async function restoreAdminSession(){if(!enabled){await selectActivity(code);return}$('#adminGateMsg').textContent='Comprobando sesión docente…';const user=await store.restoreAdmin();if(!user){$('#adminGateMsg').textContent='';return}adminReady=true;setAdminView(true);await selectActivity(code)}
restoreAdminSession();
