import{store,enabled}from'./firebase.js?v=11';
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="map.css">');
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="map-background.css?v=8">');
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="map-tweaks.css">');
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="route-requirements.css">');
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="node-state.css">');
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="route-arrows.css">');
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="pending-drag.css">');
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="round-objective.css?v=8">');
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="leaderboard-timing.css?v=1">');
const D=window.ODYSSEY_DATA,$=s=>document.querySelector(s);
let team,experienceCode='',nodeCount=10,activeNodeIds=[],nodePositions={},roundNo=1,metric='distance',route=['troy','ithaca'],active=false,attempts=[];
const validMetric=value=>D.metrics[value]?value:'distance';
const place=id=>D.places.find(p=>p.id===id);
const mapPoint=p=>nodePositions[p.id]||p;
const activePlaces=()=>{if(activeNodeIds.length)return D.places.filter(p=>activeNodeIds.includes(p.id));const middle=D.places.filter(p=>!p.required).sort((a,b)=>a.order-b.order).slice(0,Math.max(3,nodeCount-2));return[D.places.find(p=>p.id==='troy'),...middle,D.places.find(p=>p.id==='ithaca')]};
const configurationNodeIds=()=>activePlaces().map(p=>p.id),currentConfigurationKey=()=>D.configurationKey(roundNo,metric,configurationNodeIds());
const timerKey=()=>`odisea:timer:${team?.id||'equipo'}:${currentConfigurationKey()}`;
function ensureTimer(){const key=timerKey(),stored=Number(localStorage.getItem(key));if(!stored){const started=Date.now();localStorage.setItem(key,String(started));return started}return stored}
const formatDuration=value=>{if(!Number.isFinite(Number(value)))return'—';const seconds=Math.max(0,Math.round(Number(value)/1000)),minutes=Math.floor(seconds/60);return minutes?`${minutes}:${String(seconds%60).padStart(2,'0')}`:`${seconds} s`};
const missingPlaces=()=>activePlaces().filter(p=>!route.includes(p.id));
const routeComplete=()=>missingPlaces().length===0&&route[0]==='troy'&&route.at(-1)==='ithaca'&&route.length===activePlaces().length;
const routeFeasible=()=>D.score(route,D.rounds[roundNo-1],metric).feasible;
$('#mode').textContent=enabled?'Conectado a Firebase':'Modo demostración · datos locales';
document.querySelector('.map-head>p').textContent='Pasa el cursor por un punto para conocer su historia. Arrastra los lugares pendientes hasta una flecha de la carta de navegación.';
$('#map').insertAdjacentHTML('afterend',`<p class="map-credit">Mapa adaptado a partir de <a href="https://www.worldhistory.org/image/15906/map-of-odysseus-10-year-journey-home/" target="_blank" rel="noopener noreferrer">“Map of Odysseus’ 10-year Journey Home”</a>, de Simeon Netchev, publicado por World History Encyclopedia. Obra original bajo licencia <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank" rel="noopener noreferrer">CC BY-NC-ND 4.0</a>.</p>`);
$('#mode').insertAdjacentHTML('beforebegin','<p id="loginError" class="login-error" role="alert"></p>');
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginError').textContent='';try{experienceCode=$('#accessCode').value.trim();team=await store.join(experienceCode,{name:$('#teamName').value.trim()});const config=await store.load(experienceCode);active=!!config.active;nodeCount=config.nodeCount||10;activeNodeIds=config.activeNodeIds||[];nodePositions=config.nodePositions||{};roundNo=config.round||1;metric=validMetric(config.objectiveMetric);route=['troy','ithaca'];ensureTimer();$('#login').hidden=true;$('#game').hidden=false;$('#teamBadge').innerHTML=`${team.name}<small>● ${experienceCode}</small>`;store.watchExp(experienceCode,x=>{if(x){const previousKey=currentConfigurationKey(),nextRound=x.round||1,nextMetric=validMetric(x.objectiveMetric);active=!!x.active;nodeCount=x.nodeCount||10;activeNodeIds=x.activeNodeIds||[];nodePositions=x.nodePositions||{};roundNo=nextRound;metric=nextMetric;const problemChanged=previousKey!==currentConfigurationKey();if(problemChanged){route=['troy','ithaca'];ensureTimer()}else{route=route.filter(id=>activePlaces().some(p=>p.id===id));if(!route.includes('troy'))route.unshift('troy');if(!route.includes('ithaca'))route.push('ithaca')}render()}});store.watchBoard(experienceCode,x=>{attempts=x;renderBoard()});render()}catch(error){$('#loginError').textContent=error.message}};
function render(){const r=D.rounds[roundNo-1],metricInfo=D.metrics[metric];$('#roundLabel').textContent=`Ronda activa ${roundNo} de 3`;$('#roundTitle').textContent=r.title;$('#roundStory').textContent=r.story;$('#roundTabs').innerHTML=`<span>RONDA ${roundNo} · ${r.title.toUpperCase()}</span>`;$('#metricAssigned').textContent=metricInfo[0];$('#metricUnit').textContent=metricInfo[1];document.querySelector('.leader .overline').textContent=`En vivo · misma configuración · ${configurationNodeIds().length} lugares`;renderRoute();renderMap();renderMatrix();renderScore();renderBoard();const missing=missingPlaces().length,feasible=routeFeasible();$('#submit').disabled=!active||!routeComplete()||!feasible;$('#submit').textContent=!active?'Actividad pausada':missing?`Faltan ${missing} lugares`:!feasible?'Hay rutas prohibidas':'Registrar decisión'}
function routeLegHtml(from,to,index){const value=D.rounds[roundNo-1].matrices[metric][from][to],unit=D.metrics[metric][1],closed=value==null;return`<div class="route-leg ${closed?'closed':''}" data-drop-index="${index+1}" aria-label="Soltar aquí, entre ${place(from).name} y ${place(to).name}. ${closed?'Ruta prohibida':`Tramo actual: ${value} ${unit}`}"><small>${closed?'CERRADA':`${value} <em>${unit}</em>`}</small><span aria-hidden="true">${closed?'×':'→'}</span></div>`}
function insertAt(id,index){if(!active||!place(id)||place(id).required)return;const next=route.filter(x=>x!==id),target=Math.max(1,Math.min(index,next.length-1));next.splice(target,0,id);route=next;render()}
function renderRoute(){const missing=missingPlaces();$('#route').innerHTML=route.map((id,i)=>`<article draggable="${!place(id).required}" data-id="${id}"><b class="${place(id).required?'anchor':''}">${place(id).short}</b><span>${place(id).name}</span>${place(id).required?'':`<button data-remove="${id}" aria-label="Quitar ${place(id).name}">×</button>`}</article>${i<route.length-1?routeLegHtml(id,route[i+1],i):''}`).join('');document.querySelectorAll('#route article[draggable="true"]').forEach(el=>{el.ondragstart=e=>{e.dataTransfer.setData('text/plain',el.dataset.id);e.dataTransfer.effectAllowed='move'}});document.querySelectorAll('[data-drop-index]').forEach(slot=>{slot.ondragover=e=>{e.preventDefault();slot.classList.add('drop-ready');e.dataTransfer.dropEffect='move'};slot.ondragleave=()=>slot.classList.remove('drop-ready');slot.ondrop=e=>{e.preventDefault();slot.classList.remove('drop-ready');insertAt(e.dataTransfer.getData('text/plain'),+slot.dataset.dropIndex)}});document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{route=route.filter(x=>x!==b.dataset.remove);render()});$('#available').innerHTML=`<div class="route-progress"><b>${route.length} de ${activePlaces().length} lugares incluidos</b><span>${missing.length?'Arrastra cada lugar hasta la flecha donde quieras insertarlo.':'Ruta completa: puedes reordenarla arrastrando un lugar hacia otra flecha.'}</span><progress max="${activePlaces().length}" value="${route.length}"></progress></div><small>Lugares pendientes · arrastra para incorporar</small><div class="pending-list">${missing.filter(p=>!p.required).map(p=>`<article class="pending-place" draggable="true" data-pending-id="${p.id}" title="Arrastra ${p.name} a una flecha"><i aria-hidden="true">⠿</i><span>${p.name}</span></article>`).join('')}</div>`;document.querySelectorAll('[data-pending-id]').forEach(el=>{el.ondragstart=e=>{e.dataTransfer.setData('text/plain',el.dataset.pendingId);e.dataTransfer.effectAllowed='move';el.classList.add('dragging')};el.ondragend=()=>el.classList.remove('dragging')});$('#routeInfo').textContent=`${route.length-2} escalas · ${route.length-1} tramos · ${activePlaces().length} nodos obligatorios`}
function renderMap(){const selected=new Set(route),sy=56.28/100,M=D.rounds[roundNo-1].matrices[metric];const paths=route.slice(0,-1).map((id,i)=>{const next=route[i+1],a=mapPoint(place(id)),b=mapPoint(place(next)),closed=M[id][next]==null,cy=Math.min(96,Math.max(a.y,b.y)+5)*sy,cx=(a.x+b.x)/2,d=`M ${a.x} ${a.y*sy} Q ${cx} ${cy} ${b.x} ${b.y*sy}`;return`<path class="route-halo" d="${d}"/><path class="route-path ${closed?'closed-path':''}" d="${d}" ${closed?'':'marker-end="url(#arrow)"'}/>`}).join('');const nodes=activePlaces().map((p,i)=>{const pos=mapPoint(p),chosen=selected.has(p.id);return`<button class="student-node ${chosen?'selected':'pending'}" data-map-place="${p.id}" style="left:${pos.x}%;top:${pos.y}%" aria-label="Información sobre ${p.name}">${i+1}</button>`}).join('');$('#map').innerHTML=`<svg viewBox="0 0 100 56.28" role="img" aria-label="Mapa con ${activePlaces().length} locaciones activas"><defs><marker id="arrow" markerUnits="userSpaceOnUse" markerWidth="1.45" markerHeight="1.45" refX="1.3" refY=".725" orient="auto"><path d="M0,0 L1.45,.725 L0,1.45 Z"/></marker></defs>${paths}</svg>${nodes}<article id="mapTooltip" class="map-tooltip" hidden></article>`;document.querySelectorAll('[data-map-place]').forEach(node=>{const show=()=>showMapTooltip(node.dataset.mapPlace),hide=()=>{$('#mapTooltip').hidden=true};node.onmouseenter=show;node.onfocus=show;node.onclick=show;node.onmouseleave=hide;node.onblur=hide})}
function showMapTooltip(id){const p=place(id),pos=mapPoint(p),tip=$('#mapTooltip');tip.innerHTML=`<p>${p.kind}</p><h3>${p.name}</h3><small>${p.book}</small><span>${p.story}</span><b>Hoy</b><span>${p.modern}</span>`;tip.style.left=Math.min(55,Math.max(2,pos.x))+'%';tip.style.top=Math.min(70,Math.max(2,pos.y+4))+'%';tip.hidden=false}
function renderMatrix(){const list=activePlaces(),M=D.rounds[roundNo-1].matrices[metric],unit=D.metrics[metric][1],used=new Set(route.slice(0,-1).map((x,i)=>`${x}-${route[i+1]}`));$('#matrixTitle').textContent=`Matriz de ${D.metrics[metric][0].toLowerCase()} · ${unit}`;$('#matrix').innerHTML=`<table><thead><tr><th>Desde ↓ / Hacia →</th>${list.map(p=>`<th title="${p.name}">${p.short}</th>`).join('')}</tr></thead><tbody>${list.map(a=>`<tr><th>${a.short}<small>${a.name}</small></th>${list.map(b=>{const value=M[a.id][b.id],closed=a.id!==b.id&&value==null;return`<td class="${a.id===b.id?'zero':''} ${closed?'blocked':''} ${used.has(`${a.id}-${b.id}`)?'used':''}" title="${a.name} → ${b.name}${closed?' · Ruta prohibida':''}">${a.id===b.id?'—':closed?'×':value}</td>`}).join('')}</tr>`).join('')}</tbody></table>`}
function renderScore(){const r=D.score(route,D.rounds[roundNo-1],metric);$('#total').innerHTML=r.feasible?`${r.total}<small>${D.metrics[metric][1]}</small>`:`<span class="closed-total">Ruta cerrada</span>`;$('#legs').innerHTML=r.legs.map(l=>`<span class="${l.value==null?'closed-leg':''}">${place(l.from).name} → ${place(l.to).name}<b>${l.value==null?'×':l.value}</b></span>`).join('')}
function renderBoard(){const key=currentConfigurationKey(),best={},isBetter=(a,b)=>a.score<b.score||(a.score===b.score&&(a.durationMs??Infinity)<(b.durationMs??Infinity));attempts.filter(a=>a.configurationKey===key).forEach(a=>{if(!best[a.teamId]||isBetter(a,best[a.teamId]))best[a.teamId]=a});const sorted=Object.values(best).sort((a,b)=>a.score-b.score||(a.durationMs??Infinity)-(b.durationMs??Infinity));$('#leaderboard').innerHTML=sorted.length?sorted.map((a,i)=>`<div class="${team&&a.teamId===team.id?'me':''}"><i>${String(i+1).padStart(2,'0')}</i><span>${a.teamName||a.teamId}</span><b>${a.score} <small>${D.metrics[metric][1]}</small><em>${formatDuration(a.durationMs)}</em></b></div>`).join(''):'<p class="empty-board">Aún no hay resultados validados para esta configuración.</p>'}
$('#submit').onclick=async()=>{const result=D.score(route,D.rounds[roundNo-1],metric);if(!active||!routeComplete()||!result.feasible)return;const nodes=configurationNodeIds(),durationMs=Math.max(0,Date.now()-ensureTimer()),configurationName=`${D.rounds[roundNo-1].title} · ${D.metrics[metric][0]} · ${nodes.length} lugares`,payload={activityCode:experienceCode,configurationName,round:roundNo,metric,route:[...route],score:result.total,durationMs,nodeCount:nodes.length,activeNodeIds:nodes,configurationKey:D.configurationKey(roundNo,metric,nodes)};await store.save(experienceCode,team,payload);$('#submit').textContent='Ruta enviada para validación ✓';setTimeout(()=>render(),1800)};
