import{store,enabled}from'./firebase.js?v=11';
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="map.css">');
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="map-background.css?v=8">');
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="map-tweaks.css">');
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="route-requirements.css">');
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="node-state.css">');
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="route-arrows.css">');
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="pending-drag.css">');
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="round-objective.css?v=8">');
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="leaderboard-timing.css?v=1">');
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="student.css?v=10">');
const D=window.ODYSSEY_DATA,$=s=>document.querySelector(s);
let team,experienceCode='',nodeCount=10,activeNodeIds=[],nodePositions={},roundNo=1,metric='distance',route=['troy','ithaca'],active=false,attempts=[],selectedPlaceId=null;
const validMetric=value=>D.metrics[value]?value:'distance';
const place=id=>D.places.find(p=>p.id===id);
const mapPoint=p=>nodePositions[p.id]||p;
const activePlaces=()=>{if(activeNodeIds.length)return D.places.filter(p=>activeNodeIds.includes(p.id));const middle=D.places.filter(p=>!p.required).sort((a,b)=>a.order-b.order).slice(0,Math.max(3,nodeCount-2));return[D.places.find(p=>p.id==='troy'),...middle,D.places.find(p=>p.id==='ithaca')]};
const emptyRoute=()=>['troy',...Array(Math.max(0,activePlaces().length-2)).fill(null),'ithaca'];
const placedRoute=()=>route.filter(Boolean);
const configurationNodeIds=()=>activePlaces().map(p=>p.id),currentConfigurationKey=()=>D.configurationKey(roundNo,metric,configurationNodeIds());
const timerKey=()=>`odisea:timer:${team?.id||'equipo'}:${currentConfigurationKey()}`;
function ensureTimer(){const key=timerKey(),stored=Number(localStorage.getItem(key));if(!stored){const started=Date.now();localStorage.setItem(key,String(started));return started}return stored}
const formatDuration=value=>{if(!Number.isFinite(Number(value)))return'—';const seconds=Math.max(0,Math.round(Number(value)/1000)),minutes=Math.floor(seconds/60);return minutes?`${minutes}:${String(seconds%60).padStart(2,'0')}`:`${seconds} s`};
const missingPlaces=()=>activePlaces().filter(p=>!route.includes(p.id));
const routeComplete=()=>missingPlaces().length===0&&!route.includes(null)&&route[0]==='troy'&&route.at(-1)==='ithaca'&&route.length===activePlaces().length;
const routeFeasible=()=>!routeComplete()||D.score(route,D.rounds[roundNo-1],metric).feasible;
$('#mode').textContent=enabled?'Conectado a Firebase':'Modo demostración · datos locales';
document.querySelector('.map-head>p').textContent='Los números indican el orden actual de la ruta. Los puntos sin número todavía están pendientes.';
$('#map').insertAdjacentHTML('afterend',`<p class="map-credit">Mapa adaptado a partir de <a href="https://www.worldhistory.org/image/15906/map-of-odysseus-10-year-journey-home/" target="_blank" rel="noopener noreferrer">“Map of Odysseus’ 10-year Journey Home”</a>, de Simeon Netchev, publicado por World History Encyclopedia. Obra original bajo licencia <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank" rel="noopener noreferrer">CC BY-NC-ND 4.0</a>.</p>`);
$('#mode').insertAdjacentHTML('beforebegin','<p id="loginError" class="login-error" role="alert"></p>');
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginError').textContent='';try{experienceCode=$('#accessCode').value.trim();team=await store.join(experienceCode,{name:$('#teamName').value.trim()});const config=await store.load(experienceCode);active=!!config.active;nodeCount=config.nodeCount||10;activeNodeIds=config.activeNodeIds||[];nodePositions=config.nodePositions||{};roundNo=config.round||1;metric=validMetric(config.objectiveMetric);route=emptyRoute();selectedPlaceId=null;ensureTimer();$('#login').hidden=true;$('#game').hidden=false;$('#teamBadge').innerHTML=`${team.name}<small>● ${experienceCode}</small>`;store.watchExp(experienceCode,x=>{if(x){const previousKey=currentConfigurationKey(),nextRound=x.round||1,nextMetric=validMetric(x.objectiveMetric);active=!!x.active;nodeCount=x.nodeCount||10;activeNodeIds=x.activeNodeIds||[];nodePositions=x.nodePositions||{};roundNo=nextRound;metric=nextMetric;const problemChanged=previousKey!==currentConfigurationKey();if(problemChanged){route=emptyRoute();selectedPlaceId=null;ensureTimer()}else{const allowed=new Set(activePlaces().map(p=>p.id)),kept=route.slice(1,-1).filter(id=>id&&allowed.has(id));route=emptyRoute();kept.slice(0,-2+route.length).forEach((id,i)=>route[i+1]=id);if(selectedPlaceId&&!allowed.has(selectedPlaceId))selectedPlaceId=null}render()}});store.watchBoard(experienceCode,x=>{attempts=x;renderBoard()});render()}catch(error){$('#loginError').textContent=error.message}};
function render(){const r=D.rounds[roundNo-1],metricInfo=D.metrics[metric];$('#roundLabel').textContent=`Ronda activa ${roundNo} de 3`;$('#roundTitle').textContent=r.title;$('#roundStory').textContent=r.story;$('#roundTabs').innerHTML=`<span>RONDA ${roundNo} · ${r.title.toUpperCase()}</span>`;$('#metricAssigned').textContent=metricInfo[0];$('#metricUnit').textContent=metricInfo[1];document.querySelector('.leader .overline').textContent=`En vivo · misma configuración · ${configurationNodeIds().length} lugares`;renderRoute();renderMap();renderMatrix();renderScore();renderBoard();const missing=missingPlaces().length,feasible=routeFeasible();$('#submit').disabled=!active||!routeComplete()||!feasible;$('#submit').textContent=!active?'Actividad pausada':missing?`Faltan ${missing} lugares`:!feasible?'Hay rutas prohibidas':'Registrar decisión'}
function routeLegHtml(from,to){const ready=from&&to,value=ready?D.rounds[roundNo-1].matrices[metric][from][to]:null,unit=D.metrics[metric][1],closed=ready&&value==null;return`<div class="itinerary-leg ${!ready?'waiting':''} ${closed?'closed':''}" aria-label="${!ready?'Tramo pendiente':closed?'Ruta prohibida':`Tramo de ${value} ${unit}`}" role="note"><span aria-hidden="true">${closed?'×':'↓'}</span><small>${!ready?'Tramo pendiente':closed?'RUTA PROHIBIDA':`${value} <em>${unit}</em>`}</small></div>`}
function placeInSlot(id,index){if(!active||!place(id)||place(id).required||index<=0||index>=route.length-1)return;const source=route.indexOf(id),target=route[index];if(source===index){selectedPlaceId=null;render();return}if(source>0&&source<route.length-1)route[source]=target||null;route[index]=id;selectedPlaceId=null;render()}
function clearSlot(index){if(index>0&&index<route.length-1){route[index]=null;render()}}
function forbiddenEndpointState(index,M){const id=route[index];if(!id)return'';const incoming=index>0&&route[index-1]&&M[route[index-1]][id]==null,outgoing=index<route.length-1&&route[index+1]&&M[id][route[index+1]]==null;return incoming&&outgoing?'connection':incoming?'arrival':outgoing?'departure':''}
function renderRoute(){
  const missing=missingPlaces();
  const M=D.rounds[roundNo-1].matrices[metric];
  const rows=route.map((id,index)=>{const p=id?place(id):null,anchor=index===0||index===route.length-1,role=index===0?'Origen':index===route.length-1?'Destino':`Escala ${index}`,forbiddenState=forbiddenEndpointState(index,M),forbiddenLabel=forbiddenState==='connection'?'conexión prohibida':forbiddenState==='arrival'?'llegada prohibida':forbiddenState==='departure'?'salida prohibida':'';return`${index?routeLegHtml(route[index-1],id):''}<div class="itinerary-row ${anchor?'anchor':''} ${p?'filled':'empty'} ${forbiddenState?'forbidden-endpoint':''} ${selectedPlaceId&&!anchor?'selectable':''}" data-route-place="${p?.id||''}"><span class="itinerary-order">${String(index+1).padStart(2,'0')}</span><article class="route-slot ${anchor?'anchor':''} ${p?'filled':'empty'} ${forbiddenState?'forbidden-endpoint':''}" ${!anchor?`data-slot-index="${index}"`:''} ${p&&!anchor?`draggable="true" data-id="${p.id}"`:''} tabindex="${anchor?'-1':'0'}" aria-label="${p?`${p.name}, ${role}${forbiddenState?`, extremo de una ruta prohibida; ${forbiddenLabel}`:''}`:`Escala vacía ${index} de ${route.length-2}`}"><b>${p?p.short:'+'}</b><span><strong>${p?p.name:'Agregar localidad'}</strong><small>${p?forbiddenState?`${role} · ${forbiddenLabel}`:role:selectedPlaceId?'Pulsa para ubicar la selección':'Arrastra o selecciona una escala'}</small></span>${p&&!anchor?`<button data-clear-slot="${index}" aria-label="Quitar ${p.name}">×</button>`:''}</article></div>`}).join('');
  $('#route').innerHTML=`<div class="itinerary" aria-label="Secuencia de navegación">${rows}</div>`;
  document.querySelectorAll('#route [draggable="true"]').forEach(el=>{el.ondragstart=e=>{e.dataTransfer.setData('text/plain',el.dataset.id);e.dataTransfer.effectAllowed='move';el.classList.add('dragging')};el.ondragend=()=>el.classList.remove('dragging')});
  document.querySelectorAll('[data-slot-index]').forEach(slot=>{const index=+slot.dataset.slotIndex;slot.ondragover=e=>{e.preventDefault();slot.classList.add('drop-ready');e.dataTransfer.dropEffect='move'};slot.ondragleave=()=>slot.classList.remove('drop-ready');slot.ondrop=e=>{e.preventDefault();slot.classList.remove('drop-ready');placeInSlot(e.dataTransfer.getData('text/plain'),index)};slot.onclick=()=>{if(selectedPlaceId)placeInSlot(selectedPlaceId,index)}});
  document.querySelectorAll('[data-clear-slot]').forEach(b=>b.onclick=e=>{e.stopPropagation();clearSlot(+b.dataset.clearSlot)});
  const selected=selectedPlaceId?place(selectedPlaceId):null;
  $('#available').innerHTML=`<div class="route-progress"><b>${placedRoute().length} de ${activePlaces().length} lugares incluidos</b><span>${selected?`${selected.name} seleccionado: pulsa un espacio de la ruta.`:missing.length?'Selecciona una escala y luego un espacio, o arrástrala directamente.':'Ruta completa: arrastra una escala sobre otra para intercambiarlas.'}</span></div><small>Escalas por ubicar · selecciona una o arrástrala</small><div class="pending-list">${missing.filter(p=>!p.required).map(p=>`<button class="pending-place ${selectedPlaceId===p.id?'selected':''}" draggable="true" data-pending-id="${p.id}" aria-pressed="${selectedPlaceId===p.id}" title="Ubicar ${p.name}"><i aria-hidden="true">⠿</i><span>${p.name}</span></button>`).join('')}</div>`;
  document.querySelectorAll('[data-pending-id]').forEach(el=>{el.ondragstart=e=>{e.dataTransfer.setData('text/plain',el.dataset.pendingId);e.dataTransfer.effectAllowed='move';el.classList.add('dragging')};el.ondragend=()=>el.classList.remove('dragging');el.onclick=()=>{selectedPlaceId=selectedPlaceId===el.dataset.pendingId?null:el.dataset.pendingId;renderRoute()}});
  bindRouteMapHighlights();
  $('#routeInfo').textContent=`${placedRoute().length-2} de ${route.length-2} escalas ubicadas · ${Math.max(0,placedRoute().length-1)} tramos visibles`;
}
function setRouteMapHighlight(id,on){if(!id)return;document.querySelectorAll(`[data-map-place="${id}"],[data-route-place="${id}"]`).forEach(el=>el.classList.toggle('is-linked',on))}
function bindRouteMapHighlights(){document.querySelectorAll('[data-route-place]').forEach(row=>{const id=row.dataset.routePlace;if(!id)return;row.onmouseenter=()=>setRouteMapHighlight(id,true);row.onmouseleave=()=>setRouteMapHighlight(id,false);row.onfocusin=()=>setRouteMapHighlight(id,true);row.onfocusout=()=>setRouteMapHighlight(id,false)})}
const SEA_APPROACH={troy:[88,53],ithaca:[70,55],ismarus:[83,43],cape_malea:[76,67],cythera:[73,72],lotophagi:[41,73],cyclopes:[47,61],aeolia:[42,68],lamos:[27,64],aeaea:[19,50],cimmerians:[15,44],sirens:[38,52],scylla:[59,56],charybdis:[59,64],thrinacia:[50,73],ogygia:[13,58],scheria:[38,39]};
function seaLaneY(x){if(x<35)return 59;if(x<45)return 59+(x-35)*.9;if(x<68)return 68;if(x<86)return 68-(x-68)*.18;return 64-(x-86)*.35}
function mapPort(point,approach,sy,type){const center={x:point.x,y:point.y*sy},target={x:approach[0],y:approach[1]*sy},dx=target.x-center.x,dy=target.y-center.y,length=Math.hypot(dx,dy)||1,ux=dx/length,uy=dy/length,separation=type==='arrival'?.42:-.42;return{x:center.x+ux*1.08-uy*separation,y:center.y+uy*1.08+ux*separation}}
function smoothSvgPath(points){if(points.length<2)return'';if(points.length===2)return`M ${points[0].x} ${points[0].y} L ${points[1].x} ${points[1].y}`;let d=`M ${points[0].x} ${points[0].y} L ${points[1].x} ${points[1].y}`;for(let i=2;i<points.length;i++){const previous=points[i-1],current=points[i],last=i===points.length-1,mid={x:(previous.x+current.x)/2,y:(previous.y+current.y)/2};d+=last?` Q ${previous.x} ${previous.y} ${current.x} ${current.y}`:` Q ${previous.x} ${previous.y} ${mid.x} ${mid.y}`}return d}
function maritimePath(fromId,toId,index,sy){const from=mapPoint(place(fromId)),to=mapPoint(place(toId)),fromApproach=SEA_APPROACH[fromId]||[from.x,seaLaneY(from.x)],toApproach=SEA_APPROACH[toId]||[to.x,seaLaneY(to.x)],offset=((index%5)-2)*.58,points=[mapPort(from,fromApproach,sy,'departure'),{x:fromApproach[0],y:fromApproach[1]*sy}],distance=Math.abs(toApproach[0]-fromApproach[0]);if(distance>13){const direction=Math.sign(toApproach[0]-fromApproach[0])||1,step=12*direction;for(let x=fromApproach[0]+step;direction>0?x<toApproach[0]-5:x>toApproach[0]+5;x+=step)points.push({x,y:(seaLaneY(x)+offset)*sy})}points.push({x:toApproach[0],y:toApproach[1]*sy},mapPort(to,toApproach,sy,'arrival'));return smoothSvgPath(points)}
function renderMap(){const sy=56.28/100,M=D.rounds[roundNo-1].matrices[metric],currentRoute=placedRoute(),routeOrder=new Map(currentRoute.map((id,index)=>[id,index+1])),forbiddenEndpoints=new Set(currentRoute.slice(0,-1).flatMap((id,index)=>M[id][currentRoute[index+1]]==null?[id,currentRoute[index+1]]:[]));const paths=currentRoute.slice(0,-1).map((id,i)=>{const next=currentRoute[i+1],closed=M[id][next]==null,d=maritimePath(id,next,i,sy);return`<path class="route-halo ${closed?'closed-halo':''}" d="${d}"/><path class="route-path ${closed?'closed-path':''}" d="${d}" marker-end="url(#${closed?'blockedArrow':'arrow'})"/>`}).join('');const nodes=activePlaces().map(p=>{const pos=mapPoint(p),order=routeOrder.get(p.id),chosen=Number.isFinite(order),forbidden=forbiddenEndpoints.has(p.id);return`<button class="student-node ${chosen?'selected':'pending'} ${forbidden?'forbidden-endpoint':''}" data-map-place="${p.id}" style="left:${pos.x}%;top:${pos.y}%" aria-label="${p.name}${chosen?`, posición ${order} de la ruta`:', pendiente de ubicar'}${forbidden?', extremo de una ruta prohibida':''}">${chosen?order:''}</button>`}).join('');$('#map').innerHTML=`<svg viewBox="0 0 100 56.28" role="img" aria-label="Mapa con ${activePlaces().length} locaciones activas"><defs><marker id="arrow" markerUnits="userSpaceOnUse" markerWidth="1.15" markerHeight="1.15" refX="1.02" refY=".575" orient="auto"><path d="M0,0 L1.15,.575 L0,1.15 Z"/></marker><marker id="blockedArrow" class="blocked-arrow" markerUnits="userSpaceOnUse" markerWidth="1.25" markerHeight="1.25" refX="1.12" refY=".625" orient="auto"><path d="M0,0 L1.25,.625 L0,1.25 Z"/></marker></defs>${paths}</svg>${nodes}<article id="mapTooltip" class="map-tooltip" hidden></article>`;document.querySelectorAll('[data-map-place]').forEach(node=>{const id=node.dataset.mapPlace,show=()=>{setRouteMapHighlight(id,true);showMapTooltip(id)},hide=()=>{setRouteMapHighlight(id,false);$('#mapTooltip').hidden=true};node.onmouseenter=show;node.onfocus=show;node.onclick=show;node.onmouseleave=hide;node.onblur=hide});bindRouteMapHighlights()}
function showMapTooltip(id){const p=place(id),pos=mapPoint(p),tip=$('#mapTooltip');tip.innerHTML=`<p>${p.kind}</p><h3>${p.name}</h3><small>${p.book}</small><span>${p.story}</span><b>Hoy</b><span>${p.modern}</span>`;tip.style.left=Math.min(55,Math.max(2,pos.x))+'%';tip.style.top=Math.min(70,Math.max(2,pos.y+4))+'%';tip.hidden=false}
function renderMatrix(){const list=activePlaces(),M=D.rounds[roundNo-1].matrices[metric],unit=D.metrics[metric][1],used=new Set(route.slice(0,-1).flatMap((x,i)=>x&&route[i+1]?[`${x}-${route[i+1]}`]:[]));$('#matrixTitle').textContent=`Matriz de ${D.metrics[metric][0].toLowerCase()} · ${unit}`;$('#matrix').innerHTML=`<table><thead><tr><th>Desde ↓ / Hacia →</th>${list.map(p=>`<th title="${p.name}">${p.short}</th>`).join('')}</tr></thead><tbody>${list.map(a=>`<tr><th>${a.short}<small>${a.name}</small></th>${list.map(b=>{const value=M[a.id][b.id],closed=a.id!==b.id&&value==null;return`<td class="${a.id===b.id?'zero':''} ${closed?'blocked':''} ${used.has(`${a.id}-${b.id}`)?'used':''}" title="${a.name} → ${b.name}${closed?' · Ruta prohibida':''}">${a.id===b.id?'—':closed?'×':value}</td>`}).join('')}</tr>`).join('')}</tbody></table>`}
function renderScore(){if(!routeComplete()){$('#total').innerHTML=`—<small>${D.metrics[metric][1]}</small>`;$('#legs').innerHTML='<p class="route-score-help">Completa todos los espacios para calcular el resultado total.</p>';return}const r=D.score(route,D.rounds[roundNo-1],metric);$('#total').innerHTML=r.feasible?`${r.total}<small>${D.metrics[metric][1]}</small>`:`<span class="closed-total">Ruta cerrada</span>`;$('#legs').innerHTML=r.legs.map(l=>`<span class="${l.value==null?'closed-leg':''}">${place(l.from).name} → ${place(l.to).name}<b>${l.value==null?'×':l.value}</b></span>`).join('')}
function renderBoard(){const key=currentConfigurationKey(),best={},isBetter=(a,b)=>a.score<b.score||(a.score===b.score&&(a.durationMs??Infinity)<(b.durationMs??Infinity));attempts.filter(a=>a.configurationKey===key).forEach(a=>{if(!best[a.teamId]||isBetter(a,best[a.teamId]))best[a.teamId]=a});const sorted=Object.values(best).sort((a,b)=>a.score-b.score||(a.durationMs??Infinity)-(b.durationMs??Infinity));$('#leaderboard').innerHTML=sorted.length?sorted.map((a,i)=>`<div class="${team&&a.teamId===team.id?'me':''}"><i>${String(i+1).padStart(2,'0')}</i><span>${a.teamName||a.teamId}</span><b>${a.score} <small>${D.metrics[metric][1]}</small><em>${formatDuration(a.durationMs)}</em></b></div>`).join(''):'<p class="empty-board">Aún no hay resultados validados para esta configuración.</p>'}
$('#submit').onclick=async()=>{if(!active||!routeComplete())return;const result=D.score(route,D.rounds[roundNo-1],metric);if(!result.feasible)return;const nodes=configurationNodeIds(),durationMs=Math.max(0,Date.now()-ensureTimer()),configurationName=`${D.rounds[roundNo-1].title} · ${D.metrics[metric][0]} · ${nodes.length} lugares`,payload={activityCode:experienceCode,configurationName,round:roundNo,metric,route:[...route],score:result.total,durationMs,nodeCount:nodes.length,activeNodeIds:nodes,configurationKey:D.configurationKey(roundNo,metric,nodes)};await store.save(experienceCode,team,payload);$('#submit').textContent='Ruta enviada para validación ✓';setTimeout(()=>render(),1800)};
