(()=>{
 const D=window.ODYSSEY_DATA,$=selector=>document.querySelector(selector),safe=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
 let config;try{config=JSON.parse(localStorage.getItem('odisea:print-sheet')||'null')}catch{config=null}
 if(!config){$('#sheet').hidden=true;$('#printError').hidden=false;$('#printError').textContent='No hay una configuración preparada para imprimir. Vuelva al panel docente y seleccione Imprimir ficha.';return}
 const round=D.rounds[(+config.round||1)-1],metric=D.metrics[config.metric]||D.metrics.distance,ids=new Set(config.activeNodeIds||[]),places=D.places.filter(place=>ids.has(place.id)),matrix=round.matrices[config.metric]||round.matrices.distance,teacher=config.mode==='teacher';
 document.body.dataset.nodes=places.length;document.body.classList.toggle('teacher-mode',teacher);$('#sheetTitle').textContent=teacher?'Pauta docente':'Ficha de navegación';$('#activityName').textContent=config.code||'Sin nombre';$('#roundName').textContent=`${round.id} · ${round.title}`;$('#metricName').textContent=`${metric[0]} · ${metric[1]}`;$('#roundStory').textContent=round.story;$('#generatedDate').textContent=new Date(config.createdAt||Date.now()).toLocaleString('es-CL');
 $('#printMatrix').innerHTML=`<table><thead><tr><th>DE ↓ / A →</th>${places.map(place=>`<th title="${safe(place.name)}">${safe(place.short)}</th>`).join('')}</tr></thead><tbody>${places.map(from=>`<tr><th>${safe(from.short)}</th>${places.map(to=>{const value=matrix[from.id][to.id],diagonal=from.id===to.id,blocked=!diagonal&&value==null;return`<td class="${diagonal?'diagonal':''} ${blocked?'blocked':''}">${diagonal?'—':blocked?'×':safe(value)}</td>`}).join('')}</tr>`).join('')}</tbody></table>`;
 $('#placeLegend').innerHTML=places.map(place=>`<span><b>${safe(place.short)}</b>${safe(place.name)}</span>`).join('');
 if(teacher){$('.student-answer').hidden=true;$('.teacher-answer').hidden=false;const optimal=config.optimal;$('#teacherRoute').textContent=optimal?.route?.map(id=>D.places.find(place=>place.id===id)?.name||id).join(' → ')||'No disponible';$('#teacherValue').textContent=optimal?`${optimal.value} ${metric[1]}`:'No disponible';$('#teacherMethod').textContent=optimal?.method||''}
 $('#printButton').onclick=()=>window.print();$('#closeButton').onclick=()=>window.close();
})();
